use chrono::{DateTime, Utc};
use std::ops::{BitAnd, BitOr, Not};

/// A dynamic value type used in ORM expressions and query parameters.
#[derive(Debug, Clone, PartialEq)]
pub enum Value {
    /// 64-bit integer value.
    I64(i64),
    /// 64-bit floating point value.
    F64(f64),
    /// Text string value.
    Text(String),
    /// Boolean value.
    Bool(bool),
    /// UTC timestamp value.
    DateTime(DateTime<Utc>),
    /// Database NULL value.
    Null,
}

impl From<i64> for Value {
    fn from(v: i64) -> Self {
        Value::I64(v)
    }
}

impl From<f64> for Value {
    fn from(v: f64) -> Self {
        Value::F64(v)
    }
}

impl From<String> for Value {
    fn from(v: String) -> Self {
        Value::Text(v)
    }
}

impl From<&str> for Value {
    fn from(v: &str) -> Self {
        Value::Text(v.to_string())
    }
}

impl From<bool> for Value {
    fn from(v: bool) -> Self {
        Value::Bool(v)
    }
}

impl From<DateTime<Utc>> for Value {
    fn from(v: DateTime<Utc>) -> Self {
        Value::DateTime(v)
    }
}

impl std::fmt::Display for Value {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Value::I64(v) => write!(f, "{}", v),
            Value::F64(v) => write!(f, "{}", v),
            Value::Text(v) => write!(f, "{}", v),
            Value::Bool(v) => write!(f, "{}", v),
            Value::DateTime(v) => write!(f, "{}", v.format("%Y-%m-%d %H:%M:%S")),
            Value::Null => write!(f, "-"),
        }
    }
}

/// Comparison operators for query filtering expressions.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CompareOp {
    /// Exact equality comparison (`=`).
    Eq,
    /// Less-than comparison (`<`).
    Lt,
    /// Less-than-or-equal comparison (`<=`).
    Lte,
    /// Greater-than comparison (`>`).
    Gt,
    /// Greater-than-or-equal comparison (`>=`).
    Gte,
    /// Case-sensitive substring search (`LIKE '%val%'`).
    Contains,
    /// Case-insensitive substring search (`ILIKE '%val%'`).
    IContains,
    /// Prefix string match (`LIKE 'val%'`).
    StartsWith,
    /// Suffix string match (`LIKE '%val'`).
    EndsWith,
}

/// Resolved boolean expression tree for query WHERE clauses.
#[derive(Debug, Clone, PartialEq)]
pub enum Expr {
    /// A single field comparison expression.
    Compare {
        /// Target field name on the model.
        field: &'static str,
        /// Comparison operator.
        op: CompareOp,
        /// Comparison value.
        value: Value,
    },
    /// Conjunction of multiple expressions (AND).
    And(Vec<Expr>),
    /// Disjunction of multiple expressions (OR).
    Or(Vec<Expr>),
    /// Negation of an expression (NOT).
    Not(Box<Expr>),
}

impl BitAnd for Expr {
    type Output = Self;

    fn bitand(self, rhs: Self) -> Self {
        match (self, rhs) {
            (Expr::And(mut l), Expr::And(r)) => {
                l.extend(r);
                Expr::And(l)
            }
            (Expr::And(mut l), r) => {
                l.push(r);
                Expr::And(l)
            }
            (l, Expr::And(mut r)) => {
                r.insert(0, l);
                Expr::And(r)
            }
            (l, r) => Expr::And(vec![l, r]),
        }
    }
}

impl BitOr for Expr {
    type Output = Self;

    fn bitor(self, rhs: Self) -> Self {
        match (self, rhs) {
            (Expr::Or(mut l), Expr::Or(r)) => {
                l.extend(r);
                Expr::Or(l)
            }
            (Expr::Or(mut l), r) => {
                l.push(r);
                Expr::Or(l)
            }
            (l, Expr::Or(mut r)) => {
                r.insert(0, l);
                Expr::Or(r)
            }
            (l, r) => Expr::Or(vec![l, r]),
        }
    }
}

impl Not for Expr {
    type Output = Self;

    fn not(self) -> Self {
        Expr::Not(Box::new(self))
    }
}

/// Raw field comparison before lookup suffix resolution.
#[derive(Debug, Clone, PartialEq)]
pub struct UnresolvedCompare {
    /// Field name (possibly containing lookup suffix like `field__contains`).
    pub field: &'static str,
    /// Comparison value.
    pub value: Value,
}

/// Unresolved filter expression generated by the `q!` macro.
#[derive(Debug, Clone, PartialEq)]
pub enum UnresolvedExpr {
    /// Conjunction of unresolved field comparisons.
    And(Vec<UnresolvedCompare>),
}

/// Constructs an [`UnresolvedExpr`] for filtering querysets.
#[macro_export]
macro_rules! q {
    ($($field:ident = $value:expr),+ $(,)?) => {
        $crate::expr::UnresolvedExpr::And(vec![
            $(
                $crate::expr::UnresolvedCompare {
                    field: stringify!($field),
                    value: $crate::expr::Value::from($value),
                }
            ),+
        ])
    };
}

/// Arithmetic operators for UPDATE set expressions.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ArithOp {
    /// Addition operator (`+`).
    Add,
    /// Subtraction operator (`-`).
    Sub,
    /// Multiplication operator (`*`).
    Mul,
    /// Division operator (`/`).
    Div,
}

/// Expression specifying a value update in an UPDATE query.
#[derive(Debug, Clone, PartialEq)]
pub enum SetExpr {
    /// A literal new value.
    Literal(Value),
    /// An in-database field arithmetic operation (e.g. `col = col + 1`).
    FieldOp {
        /// Target field name on the model.
        field: &'static str,
        /// Arithmetic operator.
        op: ArithOp,
        /// Right-hand operand value.
        operand: Value,
    },
}

/// Django's F() — a reference to a field's CURRENT value in the database.
pub struct F(pub &'static str);

impl std::ops::Add<i64> for F {
    type Output = SetExpr;
    fn add(self, rhs: i64) -> SetExpr {
        SetExpr::FieldOp {
            field: self.0,
            op: ArithOp::Add,
            operand: Value::I64(rhs),
        }
    }
}

impl std::ops::Sub<i64> for F {
    type Output = SetExpr;
    fn sub(self, rhs: i64) -> SetExpr {
        SetExpr::FieldOp {
            field: self.0,
            op: ArithOp::Sub,
            operand: Value::I64(rhs),
        }
    }
}

impl std::ops::Mul<i64> for F {
    type Output = SetExpr;
    fn mul(self, rhs: i64) -> SetExpr {
        SetExpr::FieldOp {
            field: self.0,
            op: ArithOp::Mul,
            operand: Value::I64(rhs),
        }
    }
}

impl std::ops::Div<i64> for F {
    type Output = SetExpr;
    fn div(self, rhs: i64) -> SetExpr {
        SetExpr::FieldOp {
            field: self.0,
            op: ArithOp::Div,
            operand: Value::I64(rhs),
        }
    }
}

impl std::ops::Add<f64> for F {
    type Output = SetExpr;
    fn add(self, rhs: f64) -> SetExpr {
        SetExpr::FieldOp {
            field: self.0,
            op: ArithOp::Add,
            operand: Value::F64(rhs),
        }
    }
}

impl std::ops::Sub<f64> for F {
    type Output = SetExpr;
    fn sub(self, rhs: f64) -> SetExpr {
        SetExpr::FieldOp {
            field: self.0,
            op: ArithOp::Sub,
            operand: Value::F64(rhs),
        }
    }
}

impl std::ops::Mul<f64> for F {
    type Output = SetExpr;
    fn mul(self, rhs: f64) -> SetExpr {
        SetExpr::FieldOp {
            field: self.0,
            op: ArithOp::Mul,
            operand: Value::F64(rhs),
        }
    }
}

impl std::ops::Div<f64> for F {
    type Output = SetExpr;
    fn div(self, rhs: f64) -> SetExpr {
        SetExpr::FieldOp {
            field: self.0,
            op: ArithOp::Div,
            operand: Value::F64(rhs),
        }
    }
}

/// Trait implemented by types that can be converted into a [`SetExpr`].
pub trait IntoSetExpr {
    /// Converts `self` into a [`SetExpr`].
    fn into_set_expr(self) -> SetExpr;
}

impl IntoSetExpr for SetExpr {
    fn into_set_expr(self) -> SetExpr {
        self
    }
}

impl<T: Into<Value>> IntoSetExpr for T {
    fn into_set_expr(self) -> SetExpr {
        SetExpr::Literal(self.into())
    }
}

/// Constructs a vector of field assignment tuples for [`QuerySet::update`](crate::QuerySet::update).
#[macro_export]
macro_rules! set {
    ($($field:ident = $value:expr),+ $(,)?) => {
        vec![
            $(
                (stringify!($field), $crate::expr::IntoSetExpr::into_set_expr($value))
            ),+
        ]
    };
}
