use crate::error::{FromRow, OrmError};
use crate::expr::{ArithOp, CompareOp, Expr, SetExpr, UnresolvedExpr, Value};
use crate::meta::{FieldKind, Model, ModelMeta};
use djangors_db::{BindValue, DbRow, Dialect, NullKind};
use std::marker::PhantomData;

/// Resolves the correct [`NullKind`] for a field on `meta` by name.
fn null_bind_kind_for(field_name: &str, meta: &'static ModelMeta) -> NullKind {
    match meta.fields.iter().find(|f| f.name == field_name) {
        Some(f) => match f.kind {
            FieldKind::Char
            | FieldKind::Text
            | FieldKind::Email
            | FieldKind::Url
            | FieldKind::Slug
            | FieldKind::Ip
            | FieldKind::FileField => NullKind::Text,
            FieldKind::Integer | FieldKind::BigInt => NullKind::I64,
            FieldKind::Float => NullKind::F64,
            FieldKind::Boolean => NullKind::Bool,
            FieldKind::DateTime => NullKind::DateTime,
            _ => NullKind::I64,
        },
        None => NullKind::I64,
    }
}

/// Lazily constructed database query builder for model `T`.
#[derive(Debug)]
pub struct QuerySet<T: Model + FromRow> {
    filters: Vec<Expr>,
    order_by: Vec<(String, bool)>, // (column, descending)
    limit: Option<i64>,
    offset: Option<i64>,
    _marker: PhantomData<T>,
}

impl<T: Model + FromRow> Clone for QuerySet<T> {
    fn clone(&self) -> Self {
        Self {
            filters: self.filters.clone(),
            order_by: self.order_by.clone(),
            limit: self.limit,
            offset: self.offset,
            _marker: PhantomData,
        }
    }
}

impl<T: Model + FromRow> Default for QuerySet<T> {
    fn default() -> Self {
        Self::new()
    }
}

impl<T: Model + FromRow> QuerySet<T> {
    /// Creates a new empty `QuerySet` for model `T`.
    pub fn new() -> Self {
        Self {
            filters: Vec::new(),
            order_by: Vec::new(),
            limit: None,
            offset: None,
            _marker: PhantomData,
        }
    }

    /// Adds filter expressions generated by `q!` to this queryset.
    pub fn filter(mut self, expr: UnresolvedExpr) -> Result<Self, OrmError> {
        let resolved = Self::resolve_expr(expr)?;
        self.filters.push(resolved);
        Ok(self)
    }

    /// The `SELECT` this queryset would execute, for debugging and tests —
    /// Django's `str(queryset.query)`.
    pub fn debug_sql(&self) -> String {
        self.compile_select_with_order("*", true, Dialect::Postgres)
            .0
    }

    /// The bind parameters [`debug_sql`](Self::debug_sql) would send, in order.
    pub fn debug_params(&self) -> Vec<Value> {
        self.compile_select_with_order("*", true, Dialect::Postgres)
            .1
    }

    /// Excludes rows matching `expr` — the negation of [`filter`](Self::filter).
    pub fn exclude(mut self, expr: UnresolvedExpr) -> Result<Self, OrmError> {
        let resolved = Self::resolve_expr(expr)?;
        self.filters.push(Expr::Not(Box::new(resolved)));
        Ok(self)
    }

    /// Validates that `field` names a real field or relation on `T`.
    fn check_field(field: &'static str) -> Result<&'static str, OrmError> {
        let meta = T::meta();
        let exists = meta.fields.iter().any(|f| f.name == field)
            || meta.relations.iter().any(|r| r.field_name == field);
        if !exists {
            return Err(OrmError::FieldNotFound {
                field: field.to_string(),
                model: meta.struct_name,
            });
        }
        Ok(field)
    }

    /// Recursively resolves an [`UnresolvedExpr`] tree into an [`Expr`] tree.
    fn resolve_expr(expr: UnresolvedExpr) -> Result<Expr, OrmError> {
        match expr {
            UnresolvedExpr::And(compares) => {
                let mut resolved = Vec::new();
                for comp in compares {
                    let (field_name, suffix) = split_field_lookup(comp.field);
                    let field = Self::check_field(field_name)?;
                    resolved.push(Expr::Compare {
                        field,
                        op: suffix_to_op(suffix),
                        value: comp.value,
                    });
                }
                Ok(Expr::And(resolved))
            }
            UnresolvedExpr::AndFields(compares) => {
                let mut resolved = Vec::new();
                for comp in compares {
                    let (left_name, suffix) = split_field_lookup(comp.left);
                    let left = Self::check_field(left_name)?;
                    let right = Self::check_field(comp.right)?;
                    resolved.push(Expr::CompareField {
                        left,
                        op: suffix_to_op(suffix),
                        right,
                    });
                }
                Ok(Expr::And(resolved))
            }
            UnresolvedExpr::All(nodes) => {
                let mut resolved = Vec::new();
                for node in nodes {
                    resolved.push(Self::resolve_expr(node)?);
                }
                Ok(Expr::And(resolved))
            }
            UnresolvedExpr::Any(nodes) => {
                let mut resolved = Vec::new();
                for node in nodes {
                    resolved.push(Self::resolve_expr(node)?);
                }
                Ok(Expr::Or(resolved))
            }
            UnresolvedExpr::Negate(inner) => Ok(Expr::Not(Box::new(Self::resolve_expr(*inner)?))),
        }
    }

    /// Groups by `group_by` and computes `aggs` per group — Django's
    /// `.values(...).annotate(...)`.
    pub async fn annotate<E: djangors_db::DbExecutor>(
        &self,
        mut db: E,
        group_by: &[&'static str],
        aggs: Vec<(&'static str, crate::aggregate::AggExpr)>,
    ) -> Result<Vec<GroupRow>, OrmError> {
        let dialect = db.dialect();
        let meta = T::meta();

        if group_by.is_empty() {
            return Err(OrmError::InvalidQuery(
                "annotate requires at least one group-by field".to_string(),
            ));
        }

        for field in group_by {
            Self::check_field(field)?;
        }
        for (_, agg) in &aggs {
            let field_name = agg_field(agg);
            if field_name != "*" {
                Self::check_field_named(field_name)?;
            }
        }

        let field_to_col = |field_name: &str| -> String {
            if let Some(f) = meta.fields.iter().find(|f| f.name == field_name) {
                format!("\"{}\"", f.column_name)
            } else if let Some(r) = meta.relations.iter().find(|r| r.field_name == field_name) {
                format!("\"{}\"", r.field_name)
            } else {
                field_name.to_string()
            }
        };

        let group_cols: Vec<String> = group_by.iter().map(|f| field_to_col(f)).collect();

        let mut select_parts = group_cols.clone();
        for (_, agg) in &aggs {
            select_parts.push(agg_sql(agg, &field_to_col, dialect));
        }

        let mut clean_qs = self.clone();
        clean_qs.limit = None;
        clean_qs.offset = None;
        let (mut sql, params) =
            clean_qs.compile_select_with_order(&select_parts.join(", "), false, dialect);
        sql.push_str(&format!(" GROUP BY {}", group_cols.join(", ")));

        let bind_values: Vec<BindValue> = params.into_iter().map(BindValue::from).collect();
        db.record_query();
        let rows = db.conn().fetch_all(&sql, &bind_values).await?;

        let mut out = Vec::with_capacity(rows.len());
        for row in &rows {
            let mut keys = Vec::with_capacity(group_by.len());
            for (i, field) in group_by.iter().enumerate() {
                keys.push((*field, decode_value(row, i, field_kind_of(field, meta))));
            }

            let mut aggregates = Vec::with_capacity(aggs.len());
            for (i, (alias, agg)) in aggs.iter().enumerate() {
                let idx = group_by.len() + i;
                let res = match agg {
                    crate::aggregate::AggExpr::Count { .. } => row
                        .try_i64(idx)
                        .ok()
                        .flatten()
                        .map(crate::aggregate::AggResult::I64)
                        .unwrap_or(crate::aggregate::AggResult::Null),
                    _ => row
                        .try_f64(idx)
                        .ok()
                        .flatten()
                        .map(crate::aggregate::AggResult::F64)
                        .unwrap_or(crate::aggregate::AggResult::Null),
                };
                aggregates.push(((*alias).to_string(), res));
            }

            out.push(GroupRow { keys, aggregates });
        }

        Ok(out)
    }

    /// Selects only `fields`, returning raw column values — Django's `.values()`.
    pub async fn values<E: djangors_db::DbExecutor>(
        &self,
        mut db: E,
        fields: &[&'static str],
    ) -> Result<Vec<Vec<(&'static str, Value)>>, OrmError> {
        let dialect = db.dialect();
        let meta = T::meta();

        if fields.is_empty() {
            return Err(OrmError::InvalidQuery(
                "values requires at least one field".to_string(),
            ));
        }
        for field in fields {
            Self::check_field(field)?;
        }

        let select_list = fields
            .iter()
            .map(|f| {
                if let Some(fm) = meta.fields.iter().find(|m| m.name == *f) {
                    format!("\"{}\"", fm.column_name)
                } else {
                    format!("\"{}\"", f)
                }
            })
            .collect::<Vec<_>>()
            .join(", ");

        let (sql, params) = self.compile_select_with_order(&select_list, true, dialect);
        let bind_values: Vec<BindValue> = params.into_iter().map(BindValue::from).collect();

        db.record_query();
        let rows = db.conn().fetch_all(&sql, &bind_values).await?;

        Ok(rows
            .iter()
            .map(|row| {
                fields
                    .iter()
                    .enumerate()
                    .map(|(i, f)| (*f, decode_value(row, i, field_kind_of(f, meta))))
                    .collect()
            })
            .collect())
    }

    /// Like [`values`](Self::values) but for a single field — Django's `.values_list(field, flat=True)`.
    pub async fn values_list<E: djangors_db::DbExecutor>(
        &self,
        db: E,
        field: &'static str,
    ) -> Result<Vec<Value>, OrmError> {
        let rows = self.values(db, &[field]).await?;
        Ok(rows
            .into_iter()
            .filter_map(|mut r| r.pop().map(|(_, v)| v))
            .collect())
    }

    /// Field-name validation for a non-`'static` name.
    fn check_field_named(field: &str) -> Result<(), OrmError> {
        let meta = T::meta();
        let exists = meta.fields.iter().any(|f| f.name == field)
            || meta.relations.iter().any(|r| r.field_name == field);
        if !exists {
            return Err(OrmError::FieldNotFound {
                field: field.to_string(),
                model: meta.struct_name,
            });
        }
        Ok(())
    }

    /// ILIKE-matches `term` against every field in `fields`, OR'd together.
    pub fn filter_or_icontains(
        mut self,
        fields: &[&'static str],
        term: &str,
    ) -> Result<Self, OrmError> {
        let meta = T::meta();
        let mut compares = Vec::new();
        for field_name in fields {
            if !meta.fields.iter().any(|f| f.name == *field_name) {
                return Err(OrmError::FieldNotFound {
                    field: field_name.to_string(),
                    model: meta.struct_name,
                });
            }
            compares.push(Expr::Compare {
                field: field_name,
                op: CompareOp::IContains,
                value: Value::Text(term.to_string()),
            });
        }
        self.filters.push(Expr::Or(compares));
        Ok(self)
    }

    /// Restricts to rows where `field` is in `[gte, lt)`.
    pub fn filter_datetime_range(
        mut self,
        field: &'static str,
        gte: chrono::DateTime<chrono::Utc>,
        lt: chrono::DateTime<chrono::Utc>,
    ) -> Result<Self, OrmError> {
        let meta = T::meta();
        if !meta.fields.iter().any(|f| f.name == field) {
            return Err(OrmError::FieldNotFound {
                field: field.to_string(),
                model: meta.struct_name,
            });
        }
        self.filters.push(Expr::And(vec![
            Expr::Compare {
                field,
                op: CompareOp::Gte,
                value: Value::DateTime(gte),
            },
            Expr::Compare {
                field,
                op: CompareOp::Lt,
                value: Value::DateTime(lt),
            },
        ]));
        Ok(self)
    }

    /// Restricts results to rows strictly after a keyset position.
    pub fn after(
        mut self,
        order_field: &'static str,
        order_value: Value,
        pk_field: &'static str,
        cursor_pk: i64,
        descending: bool,
    ) -> Result<Self, OrmError> {
        let meta = T::meta();
        for field in [order_field, pk_field] {
            if !meta.fields.iter().any(|f| f.name == field)
                && !meta.relations.iter().any(|r| r.field_name == field)
            {
                return Err(OrmError::FieldNotFound {
                    field: field.to_string(),
                    model: meta.struct_name,
                });
            }
        }
        let op = if descending {
            CompareOp::Lt
        } else {
            CompareOp::Gt
        };
        self.filters.push(Expr::Or(vec![
            Expr::Compare {
                field: order_field,
                op,
                value: order_value.clone(),
            },
            Expr::And(vec![
                Expr::Compare {
                    field: order_field,
                    op: CompareOp::Eq,
                    value: order_value,
                },
                Expr::Compare {
                    field: pk_field,
                    op,
                    value: Value::I64(cursor_pk),
                },
            ]),
        ]));
        Ok(self)
    }

    /// Order results by the given field. A leading `-` means descending.
    pub fn order_by(mut self, field: &str) -> Result<Self, OrmError> {
        let (clean_field, desc) = if let Some(stripped) = field.strip_prefix('-') {
            (stripped, true)
        } else {
            (field, false)
        };
        let meta = T::meta();
        let col = if let Some(f) = meta.fields.iter().find(|f| f.name == clean_field) {
            format!("\"{}\"", f.column_name)
        } else if let Some(r) = meta.relations.iter().find(|r| r.field_name == clean_field) {
            format!("\"{}\"", r.field_name)
        } else {
            return Err(OrmError::FieldNotFound {
                field: clean_field.to_string(),
                model: meta.struct_name,
            });
        };
        self.order_by.push((col, desc));
        Ok(self)
    }

    /// Restricts the maximum number of rows returned by the query.
    pub fn limit(mut self, n: i64) -> Self {
        self.limit = Some(n);
        self
    }

    /// Sets the number of rows to skip before starting to return rows.
    pub fn offset(mut self, n: i64) -> Self {
        self.offset = Some(n);
        self
    }

    /// Compiles the query to a `SELECT *` SQL string and parameter list.
    pub fn compile_select(&self) -> (String, Vec<Value>) {
        self.compile_select_custom("*")
    }

    /// Compiles the query to a SQL string selecting `select_list` columns and parameter list.
    pub fn compile_select_custom(&self, select_list: &str) -> (String, Vec<Value>) {
        self.compile_select_with_order(select_list, true, Dialect::Postgres)
    }

    /// Compiles the query with specified dialect.
    pub(crate) fn compile_select_with_order(
        &self,
        select_list: &str,
        include_order: bool,
        dialect: Dialect,
    ) -> (String, Vec<Value>) {
        let meta = T::meta();
        let mut sql = format!("SELECT {} FROM \"{}\"", select_list, meta.table_name);
        let mut params = Vec::new();
        let mut param_idx = 1;

        let field_to_col = |field_name: &str| -> String {
            if let Some(f) = meta.fields.iter().find(|f| f.name == field_name) {
                format!("\"{}\"", f.column_name)
            } else if let Some(r) = meta.relations.iter().find(|r| r.field_name == field_name) {
                format!("\"{}\"", r.field_name)
            } else {
                field_name.to_string()
            }
        };

        if !self.filters.is_empty() {
            let combined = Expr::And(self.filters.clone());
            let where_clause = compile_expr_sql(
                &combined,
                &field_to_col,
                &mut params,
                &mut param_idx,
                dialect,
            );
            sql.push_str(" WHERE ");
            sql.push_str(&where_clause);
        }

        let order_source = if !include_order {
            Vec::new()
        } else if !self.order_by.is_empty() {
            self.order_by.clone()
        } else {
            meta.ordering
                .iter()
                .map(|&field| {
                    let (clean_field, desc) = if let Some(stripped) = field.strip_prefix('-') {
                        (stripped, true)
                    } else {
                        (field, false)
                    };
                    let col = if let Some(f) = meta.fields.iter().find(|f| f.name == clean_field) {
                        format!("\"{}\"", f.column_name)
                    } else if let Some(r) =
                        meta.relations.iter().find(|r| r.field_name == clean_field)
                    {
                        format!("\"{}\"", r.field_name)
                    } else {
                        clean_field.to_string()
                    };
                    (col, desc)
                })
                .collect()
        };

        if !order_source.is_empty() {
            let order_parts: Vec<String> = order_source
                .iter()
                .map(|(col, desc)| {
                    if *desc {
                        format!("{} DESC", col)
                    } else {
                        format!("{} ASC", col)
                    }
                })
                .collect();
            sql.push_str(" ORDER BY ");
            sql.push_str(&order_parts.join(", "));
        }

        if let Some(limit) = self.limit {
            sql.push_str(&format!(" LIMIT {}", limit));
        }
        if let Some(offset) = self.offset {
            if self.limit.is_none() && dialect == Dialect::Sqlite {
                sql.push_str(" LIMIT -1");
            }
            sql.push_str(&format!(" OFFSET {}", offset));
        }

        (sql, params)
    }

    /// Executes the query and returns all matching model instances.
    pub async fn all<E: djangors_db::DbExecutor>(&self, mut db: E) -> Result<Vec<T>, OrmError> {
        let dialect = db.dialect();
        let (sql, params) = self.compile_select_with_order("*", true, dialect);
        let bind_values: Vec<BindValue> = params.into_iter().map(BindValue::from).collect();
        db.record_query();
        let rows = db.conn().fetch_all(&sql, &bind_values).await?;
        let mut results = Vec::with_capacity(rows.len());
        for row in rows {
            results.push(T::from_row(&row)?);
        }
        Ok(results)
    }

    /// Fetches a single model instance matching the query filters.
    pub async fn get<E: djangors_db::DbExecutor>(&self, db: E) -> Result<T, OrmError> {
        let mut cloned = self.clone();
        cloned.limit = Some(2);
        let results = cloned.all(db).await?;
        if results.is_empty() {
            Err(OrmError::NotFound {
                model: T::meta().struct_name,
            })
        } else if results.len() > 1 {
            Err(OrmError::MultipleObjectsReturned {
                model: T::meta().struct_name,
            })
        } else {
            Ok(results.into_iter().next().unwrap())
        }
    }

    /// Fetches the first model instance matching the query filters, or `None` if no row matches.
    pub async fn first<E: djangors_db::DbExecutor>(&self, db: E) -> Result<Option<T>, OrmError> {
        let mut cloned = self.clone();
        cloned.limit = Some(1);
        let results = cloned.all(db).await?;
        Ok(results.into_iter().next())
    }

    /// Returns `true` if at least one record matches the query filters.
    pub async fn exists<E: djangors_db::DbExecutor>(&self, mut db: E) -> Result<bool, OrmError> {
        let mut cloned = self.clone();
        cloned.limit = Some(1);
        let dialect = db.dialect();
        let (sql, params) = cloned.compile_select_with_order("1", false, dialect);
        let bind_values: Vec<BindValue> = params.into_iter().map(BindValue::from).collect();
        db.record_query();
        let row_opt = db.conn().fetch_optional(&sql, &bind_values).await?;
        Ok(row_opt.is_some())
    }

    /// Returns the total count of rows matching the query filters.
    pub async fn count<E: djangors_db::DbExecutor>(&self, mut db: E) -> Result<i64, OrmError> {
        let dialect = db.dialect();
        let (sql, params) = self.compile_select_with_order("COUNT(*)", false, dialect);
        let bind_values: Vec<BindValue> = params.into_iter().map(BindValue::from).collect();
        db.record_query();
        let row = db.conn().fetch_one(&sql, &bind_values).await?;
        let count = row.try_i64(0)?.unwrap_or(0);
        Ok(count)
    }

    /// Executes aggregate functions over matching rows.
    pub async fn aggregate<E: djangors_db::DbExecutor>(
        &self,
        mut db: E,
        aggs: Vec<crate::aggregate::AggExpr>,
    ) -> Result<Vec<crate::aggregate::AggResult>, OrmError> {
        let dialect = db.dialect();
        let meta = T::meta();

        for agg in &aggs {
            let field_name = match agg {
                crate::aggregate::AggExpr::Count { field } => *field,
                crate::aggregate::AggExpr::Sum { field } => *field,
                crate::aggregate::AggExpr::Avg { field } => *field,
                crate::aggregate::AggExpr::Min { field } => *field,
                crate::aggregate::AggExpr::Max { field } => *field,
            };

            if field_name != "*" {
                let exists = meta.fields.iter().any(|f| f.name == field_name)
                    || meta.relations.iter().any(|r| r.field_name == field_name);
                if !exists {
                    return Err(OrmError::FieldNotFound {
                        field: field_name.to_string(),
                        model: meta.struct_name,
                    });
                }
            }
        }

        let field_to_col = |field_name: &str| -> String {
            if let Some(f) = meta.fields.iter().find(|f| f.name == field_name) {
                format!("\"{}\"", f.column_name)
            } else if let Some(r) = meta.relations.iter().find(|r| r.field_name == field_name) {
                format!("\"{}\"", r.field_name)
            } else {
                field_name.to_string()
            }
        };

        let mut agg_sql_parts = Vec::new();
        for agg in &aggs {
            let part = match agg {
                crate::aggregate::AggExpr::Count { field } => {
                    if *field == "*" {
                        "COUNT(*)".to_string()
                    } else {
                        format!("COUNT({})", field_to_col(field))
                    }
                }
                crate::aggregate::AggExpr::Sum { field } => {
                    dialect.cast_float(&format!("SUM({})", field_to_col(field)))
                }
                crate::aggregate::AggExpr::Avg { field } => {
                    dialect.cast_float(&format!("AVG({})", field_to_col(field)))
                }
                crate::aggregate::AggExpr::Min { field } => {
                    dialect.cast_float(&format!("MIN({})", field_to_col(field)))
                }
                crate::aggregate::AggExpr::Max { field } => {
                    dialect.cast_float(&format!("MAX({})", field_to_col(field)))
                }
            };
            agg_sql_parts.push(part);
        }

        let select_list = agg_sql_parts.join(", ");
        let mut clean_qs = self.clone();
        clean_qs.limit = None;
        clean_qs.offset = None;

        let (sql, params) = clean_qs.compile_select_with_order(&select_list, false, dialect);
        let bind_values: Vec<BindValue> = params.into_iter().map(BindValue::from).collect();

        db.record_query();
        let row = db.conn().fetch_one(&sql, &bind_values).await?;

        let mut results = Vec::with_capacity(aggs.len());
        for (i, agg) in aggs.iter().enumerate() {
            let res = match agg {
                crate::aggregate::AggExpr::Count { .. } => {
                    let count_val = row.try_i64(i)?.unwrap_or(0);
                    crate::aggregate::AggResult::I64(count_val)
                }
                _ => {
                    let val = row.try_f64(i)?;
                    match val {
                        Some(v) => crate::aggregate::AggResult::F64(v),
                        None => crate::aggregate::AggResult::Null,
                    }
                }
            };
            results.push(res);
        }

        Ok(results)
    }

    /// Executes a bulk UPDATE query matching current filters with specified field set expressions.
    pub async fn update<E: djangors_db::DbExecutor>(
        &self,
        mut db: E,
        sets: Vec<(&'static str, SetExpr)>,
    ) -> Result<u64, OrmError> {
        let dialect = db.dialect();
        let meta = T::meta();

        for &(field_name, ref set_expr) in &sets {
            let exists_lhs = meta.fields.iter().any(|f| f.name == field_name)
                || meta.relations.iter().any(|r| r.field_name == field_name);
            if !exists_lhs {
                return Err(OrmError::FieldNotFound {
                    field: field_name.to_string(),
                    model: meta.struct_name,
                });
            }

            if let SetExpr::FieldOp {
                field: rhs_field, ..
            } = set_expr
            {
                let exists_rhs = meta.fields.iter().any(|f| f.name == *rhs_field)
                    || meta.relations.iter().any(|r| r.field_name == *rhs_field);
                if !exists_rhs {
                    return Err(OrmError::FieldNotFound {
                        field: rhs_field.to_string(),
                        model: meta.struct_name,
                    });
                }
            }
        }

        let field_to_col = |field_name: &str| -> String {
            if let Some(f) = meta.fields.iter().find(|f| f.name == field_name) {
                format!("\"{}\"", f.column_name)
            } else if let Some(r) = meta.relations.iter().find(|r| r.field_name == field_name) {
                format!("\"{}\"", r.field_name)
            } else {
                field_name.to_string()
            }
        };

        let mut bind_values: Vec<BindValue> = Vec::new();
        let mut param_idx = 1;
        let mut set_parts = Vec::new();

        for &(field_name, ref set_expr) in &sets {
            let lhs_col = field_to_col(field_name);
            let nk = null_bind_kind_for(field_name, meta);
            match set_expr {
                SetExpr::Literal(v) => {
                    set_parts.push(format!("{} = {}", lhs_col, dialect.placeholder(param_idx)));
                    let bv = match v {
                        Value::Null => BindValue::Null(nk),
                        other => BindValue::from(other.clone()),
                    };
                    bind_values.push(bv);
                    param_idx += 1;
                }
                SetExpr::FieldOp { field, op, operand } => {
                    let rhs_col = field_to_col(field);
                    let op_sql = match op {
                        ArithOp::Add => "+",
                        ArithOp::Sub => "-",
                        ArithOp::Mul => "*",
                        ArithOp::Div => "/",
                    };
                    set_parts.push(format!(
                        "{} = {} {} {}",
                        lhs_col,
                        rhs_col,
                        op_sql,
                        dialect.placeholder(param_idx)
                    ));
                    let bv = match operand {
                        Value::Null => BindValue::Null(nk),
                        other => BindValue::from(other.clone()),
                    };
                    bind_values.push(bv);
                    param_idx += 1;
                }
            }
        }

        let mut raw_params = Vec::new();
        let mut sql = format!(
            "UPDATE \"{}\" SET {}",
            meta.table_name,
            set_parts.join(", ")
        );
        if !self.filters.is_empty() {
            let combined = Expr::And(self.filters.clone());
            let where_clause = compile_expr_sql(
                &combined,
                &field_to_col,
                &mut raw_params,
                &mut param_idx,
                dialect,
            );
            sql.push_str(" WHERE ");
            sql.push_str(&where_clause);
            for p in raw_params {
                bind_values.push(BindValue::from(p));
            }
        }

        db.record_query();
        let rows_affected = db.conn().execute(&sql, &bind_values).await?;
        Ok(rows_affected)
    }

    /// Performs a low-level INSERT query for `T` returning the generated primary key ID.
    pub async fn insert_raw<E: djangors_db::DbExecutor>(
        mut db: E,
        values: Vec<(&'static str, crate::expr::Value)>,
    ) -> Result<i64, OrmError> {
        let dialect = db.dialect();
        let meta = T::meta();
        let pk_field = meta
            .fields
            .iter()
            .find(|f| f.primary_key)
            .expect("Primary key field not found");
        let pk_column = pk_field.column_name;

        let mut processed_values = Vec::new();
        for (field_name, val) in values {
            if let Some(f) = meta.fields.iter().find(|f| f.name == field_name) {
                if f.auto {
                    continue;
                }
                processed_values.push((f.column_name, val, field_name));
            } else if let Some(r) = meta.relations.iter().find(|r| r.field_name == field_name) {
                processed_values.push((r.field_name, val, field_name));
            } else {
                return Err(OrmError::FieldNotFound {
                    field: field_name.to_string(),
                    model: meta.struct_name,
                });
            }
        }

        let mut cols = Vec::new();
        let mut placeholders = Vec::new();
        let mut bind_values = Vec::new();
        for (i, (col_name, val, field_name)) in processed_values.into_iter().enumerate() {
            cols.push(format!("\"{}\"", col_name));
            placeholders.push(dialect.placeholder(i + 1));
            let nk = null_bind_kind_for(field_name, meta);
            let bv = match val {
                Value::Null => BindValue::Null(nk),
                other => BindValue::from(other),
            };
            bind_values.push(bv);
        }

        let sql = if cols.is_empty() {
            format!(
                "INSERT INTO \"{}\" DEFAULT VALUES RETURNING \"{}\"",
                meta.table_name, pk_column
            )
        } else {
            format!(
                "INSERT INTO \"{}\" ({}) VALUES ({}) RETURNING \"{}\"",
                meta.table_name,
                cols.join(", "),
                placeholders.join(", "),
                pk_column
            )
        };

        db.record_query();
        let row = db.conn().fetch_one(&sql, &bind_values).await?;
        let pk = row.try_i64(0)?.unwrap_or(0);
        Ok(pk)
    }

    /// Inserts every item in `items` in a single multi-row `INSERT` statement.
    pub async fn bulk_create<E: djangors_db::DbExecutor>(
        mut db: E,
        items: &[T],
    ) -> Result<Vec<i64>, OrmError>
    where
        T: Model,
    {
        if items.is_empty() {
            return Ok(Vec::new());
        }

        let dialect = db.dialect();
        let meta = T::meta();
        let pk_field = meta
            .fields
            .iter()
            .find(|f| f.primary_key)
            .expect("Primary key field not found");
        let pk_column = pk_field.column_name;

        let is_insertable = |field_name: &str| -> bool {
            match meta.fields.iter().find(|f| f.name == field_name) {
                Some(f) => !f.auto,
                None => meta.relations.iter().any(|r| r.field_name == field_name),
            }
        };

        let mut cols: Vec<String> = Vec::new();
        let mut col_order: Vec<&'static str> = Vec::new();
        for (field_name, _) in items[0].field_values() {
            if is_insertable(field_name) {
                let col_name = match meta.fields.iter().find(|f| f.name == field_name) {
                    Some(f) => f.column_name,
                    None => field_name,
                };
                cols.push(format!("\"{col_name}\""));
                col_order.push(field_name);
            }
        }

        let mut placeholder_groups = Vec::new();
        let mut bind_values = Vec::new();
        let mut param_idx = 1;
        for item in items {
            let values = item.field_values();
            let mut row_placeholders = Vec::new();
            for field_name in &col_order {
                let val = values
                    .iter()
                    .find(|(name, _)| name == field_name)
                    .map(|(_, v)| v.clone())
                    .unwrap_or(Value::Null);
                row_placeholders.push(dialect.placeholder(param_idx));
                let nk = null_bind_kind_for(field_name, meta);
                let bv = match val {
                    Value::Null => BindValue::Null(nk),
                    other => BindValue::from(other),
                };
                bind_values.push(bv);
                param_idx += 1;
            }
            placeholder_groups.push(format!("({})", row_placeholders.join(", ")));
        }

        let sql = format!(
            "INSERT INTO \"{}\" ({}) VALUES {} RETURNING \"{}\"",
            meta.table_name,
            cols.join(", "),
            placeholder_groups.join(", "),
            pk_column
        );

        db.record_query();
        let rows = db.conn().fetch_all(&sql, &bind_values).await?;
        let mut pks = Vec::with_capacity(rows.len());
        for row in rows {
            pks.push(row.try_i64(0)?.unwrap_or(0));
        }
        Ok(pks)
    }

    /// Deletes a record from table `T` by primary key `pk`.
    pub async fn delete_by_pk<E: djangors_db::DbExecutor>(
        mut db: E,
        pk: i64,
    ) -> Result<u64, OrmError> {
        let dialect = db.dialect();
        let meta = T::meta();
        let pk_field = meta
            .fields
            .iter()
            .find(|f| f.primary_key)
            .expect("Primary key field not found");

        let sql = format!(
            "DELETE FROM \"{}\" WHERE \"{}\" = {}",
            meta.table_name,
            pk_field.column_name,
            dialect.placeholder(1)
        );
        db.record_query();
        let rows_affected = db.conn().execute(&sql, &[BindValue::I64(pk)]).await?;
        Ok(rows_affected)
    }

    /// Eagerly loads the given relation, avoiding an N+1 query.
    pub async fn select_related<R: Model + FromRow + Clone, E: djangors_db::DbExecutor>(
        &self,
        mut db: E,
        relation_field: &'static str,
    ) -> Result<Vec<(T, Option<R>)>, OrmError> {
        let dialect = db.dialect();
        let meta = T::meta();

        let relation = meta
            .relations
            .iter()
            .find(|r| r.field_name == relation_field)
            .ok_or_else(|| OrmError::FieldNotFound {
                field: relation_field.to_string(),
                model: meta.struct_name,
            })?;

        let target_meta = (relation.target)();
        let r_meta = R::meta();
        if target_meta.struct_name != r_meta.struct_name {
            return Err(OrmError::FieldNotFound {
                field: format!(
                    "{} (target model mismatch: expected {}, found {})",
                    relation_field, r_meta.struct_name, target_meta.struct_name
                ),
                model: meta.struct_name,
            });
        }

        let select_list = format!("*, \"{}\" AS __select_related_fk", relation_field);
        let (sql, params) = self.compile_select_with_order(&select_list, true, dialect);
        let bind_values: Vec<BindValue> = params.into_iter().map(BindValue::from).collect();

        db.record_query();
        let rows = db.conn().fetch_all(&sql, &bind_values).await?;

        let mut t_records = Vec::new();
        let mut relation_ids = std::collections::HashSet::new();

        for row in rows {
            let t = T::from_row(&row)?;
            let fk_id = row.try_i64_by_name("__select_related_fk")?;
            if let Some(id) = fk_id {
                relation_ids.insert(id);
            }
            t_records.push((t, fk_id));
        }

        if relation_ids.is_empty() {
            return Ok(t_records.into_iter().map(|(t, _)| (t, None)).collect());
        }

        let r_pk_field = r_meta
            .fields
            .iter()
            .find(|f| f.primary_key)
            .ok_or_else(|| OrmError::FieldNotFound {
                field: "primary_key".to_string(),
                model: r_meta.struct_name,
            })?;
        let r_pk_col = r_pk_field.column_name;

        let relation_ids_vec: Vec<i64> = relation_ids.into_iter().collect();
        let r_placeholders: Vec<String> = (1..=relation_ids_vec.len())
            .map(|i| dialect.placeholder(i))
            .collect();
        let r_sql = format!(
            "SELECT * FROM \"{}\" WHERE \"{}\" IN ({})",
            r_meta.table_name,
            r_pk_col,
            r_placeholders.join(", ")
        );
        let r_bind_values: Vec<BindValue> = relation_ids_vec
            .iter()
            .map(|&id| BindValue::I64(id))
            .collect();

        db.record_query();
        let r_rows = db.conn().fetch_all(&r_sql, &r_bind_values).await?;

        let mut r_map = std::collections::HashMap::new();
        for r_row in r_rows {
            let r = R::from_row(&r_row)?;
            let pk_val = r_row.try_i64_by_name(r_pk_col)?.unwrap_or(0);
            r_map.insert(pk_val, r);
        }

        let mut final_results = Vec::new();
        for (t, fk_id_opt) in t_records {
            let r_opt = match fk_id_opt {
                Some(id) => r_map.get(&id).cloned(),
                None => None,
            };
            final_results.push((t, r_opt));
        }

        Ok(final_results)
    }
}

/// Batch-loads the reverse side of a foreign-key relation for already-fetched parents.
pub async fn prefetch_related<T, R, E>(
    mut db: E,
    parents: &[T],
    related_name: &str,
) -> Result<std::collections::HashMap<i64, Vec<R>>, OrmError>
where
    T: Model,
    R: Model + FromRow + Clone,
    E: djangors_db::DbExecutor,
{
    let dialect = db.dialect();
    let parent_meta = T::meta();
    let child_meta = R::meta();
    let relation = child_meta
        .relations
        .iter()
        .find(|relation| {
            relation.related_name == Some(related_name)
                && (relation.target)().struct_name == parent_meta.struct_name
        })
        .ok_or_else(|| OrmError::FieldNotFound {
            field: format!("reverse relation '{}'", related_name),
            model: child_meta.struct_name,
        })?;
    let pk_field = parent_meta
        .fields
        .iter()
        .find(|field| field.primary_key)
        .ok_or_else(|| OrmError::FieldNotFound {
            field: "primary_key".to_string(),
            model: parent_meta.struct_name,
        })?;
    let parent_ids: Vec<i64> = parents
        .iter()
        .filter_map(|parent| {
            parent
                .field_values()
                .into_iter()
                .find(|(name, _)| *name == pk_field.name)
                .and_then(|(_, value)| match value {
                    Value::I64(id) => Some(id),
                    _ => None,
                })
        })
        .collect();

    if parent_ids.is_empty() {
        return Ok(std::collections::HashMap::new());
    }

    let placeholders: Vec<String> = (1..=parent_ids.len())
        .map(|i| dialect.placeholder(i))
        .collect();
    let sql = format!(
        "SELECT * FROM \"{}\" WHERE \"{}\" IN ({})",
        child_meta.table_name,
        relation.field_name,
        placeholders.join(", ")
    );
    let bind_values: Vec<BindValue> = parent_ids.iter().map(|&id| BindValue::I64(id)).collect();

    db.record_query();
    let rows = db.conn().fetch_all(&sql, &bind_values).await?;
    let mut grouped = std::collections::HashMap::new();
    for row in rows {
        let child = R::from_row(&row)?;
        let parent_id = child
            .field_values()
            .into_iter()
            .find(|(name, _)| *name == relation.field_name)
            .and_then(|(_, value)| match value {
                Value::I64(id) => Some(id),
                _ => None,
            })
            .ok_or_else(|| OrmError::FieldNotFound {
                field: relation.field_name.to_string(),
                model: child_meta.struct_name,
            })?;
        grouped
            .entry(parent_id)
            .or_insert_with(Vec::new)
            .push(child);
    }
    Ok(grouped)
}

fn split_field_lookup(s: &'static str) -> (&'static str, &'static str) {
    if let Some(idx) = s.rfind("__") {
        let field = &s[..idx];
        let suffix = &s[idx + 2..];
        match suffix {
            "eq" | "lt" | "lte" | "gt" | "gte" | "contains" | "icontains" | "startswith"
            | "endswith" | "ne" | "iexact" | "in" | "isnull" | "regex" | "iregex" => {
                (field, suffix)
            }
            _ => (s, "eq"),
        }
    } else {
        (s, "eq")
    }
}

/// One row of a grouped aggregate query produced by [`QuerySet::annotate`].
#[derive(Debug, Clone, PartialEq)]
pub struct GroupRow {
    /// The group-by field names paired with this group's values.
    pub keys: Vec<(&'static str, Value)>,
    /// The aggregate aliases paired with their results.
    pub aggregates: Vec<(String, crate::aggregate::AggResult)>,
}

impl GroupRow {
    /// Looks up a group-key value by field name.
    pub fn key(&self, name: &str) -> Option<&Value> {
        self.keys.iter().find(|(k, _)| *k == name).map(|(_, v)| v)
    }

    /// Looks up an aggregate result by alias.
    pub fn get(&self, alias: &str) -> Option<crate::aggregate::AggResult> {
        self.aggregates
            .iter()
            .find(|(k, _)| k == alias)
            .map(|(_, v)| *v)
    }
}

fn agg_field(agg: &crate::aggregate::AggExpr) -> &'static str {
    match agg {
        crate::aggregate::AggExpr::Count { field }
        | crate::aggregate::AggExpr::Sum { field }
        | crate::aggregate::AggExpr::Avg { field }
        | crate::aggregate::AggExpr::Min { field }
        | crate::aggregate::AggExpr::Max { field } => field,
    }
}

fn agg_sql(
    agg: &crate::aggregate::AggExpr,
    field_to_col: &dyn Fn(&str) -> String,
    dialect: Dialect,
) -> String {
    match agg {
        crate::aggregate::AggExpr::Count { field } => {
            if *field == "*" {
                "COUNT(*)".to_string()
            } else {
                format!("COUNT({})", field_to_col(field))
            }
        }
        crate::aggregate::AggExpr::Sum { field } => {
            dialect.cast_float(&format!("SUM({})", field_to_col(field)))
        }
        crate::aggregate::AggExpr::Avg { field } => {
            dialect.cast_float(&format!("AVG({})", field_to_col(field)))
        }
        crate::aggregate::AggExpr::Min { field } => {
            dialect.cast_float(&format!("MIN({})", field_to_col(field)))
        }
        crate::aggregate::AggExpr::Max { field } => {
            dialect.cast_float(&format!("MAX({})", field_to_col(field)))
        }
    }
}

fn field_kind_of(name: &str, meta: &'static ModelMeta) -> Option<FieldKind> {
    meta.fields.iter().find(|f| f.name == name).map(|f| f.kind)
}

fn decode_value(row: &DbRow, idx: usize, kind: Option<FieldKind>) -> Value {
    match kind {
        Some(FieldKind::Char)
        | Some(FieldKind::Text)
        | Some(FieldKind::Email)
        | Some(FieldKind::Url)
        | Some(FieldKind::Slug)
        | Some(FieldKind::Ip)
        | Some(FieldKind::FileField) => row
            .try_string(idx)
            .ok()
            .flatten()
            .map(Value::Text)
            .unwrap_or(Value::Null),
        Some(FieldKind::Float) => row
            .try_f64(idx)
            .ok()
            .flatten()
            .map(Value::F64)
            .unwrap_or(Value::Null),
        Some(FieldKind::Boolean) => row
            .try_bool(idx)
            .ok()
            .flatten()
            .map(Value::Bool)
            .unwrap_or(Value::Null),
        Some(FieldKind::DateTime) => row
            .try_datetime(idx)
            .ok()
            .flatten()
            .map(Value::DateTime)
            .unwrap_or(Value::Null),
        _ => row
            .try_i64(idx)
            .ok()
            .flatten()
            .map(Value::I64)
            .unwrap_or(Value::Null),
    }
}

fn suffix_to_op(suffix: &str) -> CompareOp {
    match suffix {
        "eq" => CompareOp::Eq,
        "lt" => CompareOp::Lt,
        "lte" => CompareOp::Lte,
        "gt" => CompareOp::Gt,
        "gte" => CompareOp::Gte,
        "contains" => CompareOp::Contains,
        "icontains" => CompareOp::IContains,
        "startswith" => CompareOp::StartsWith,
        "endswith" => CompareOp::EndsWith,
        "ne" => CompareOp::Ne,
        "iexact" => CompareOp::IExact,
        "in" => CompareOp::In,
        "isnull" => CompareOp::IsNull,
        "regex" => CompareOp::Regex,
        "iregex" => CompareOp::IRegex,
        _ => CompareOp::Eq,
    }
}

fn compile_expr_sql(
    expr: &Expr,
    field_to_col: &dyn Fn(&str) -> String,
    params: &mut Vec<Value>,
    param_idx: &mut usize,
    dialect: Dialect,
) -> String {
    match expr {
        Expr::Compare { field, op, value } => {
            let col = field_to_col(field);

            match op {
                CompareOp::In => {
                    let items: Vec<Value> = match value {
                        Value::List(items) => items.clone(),
                        other => vec![other.clone()],
                    };
                    if items.is_empty() {
                        return "FALSE".to_string();
                    }
                    let mut placeholders = Vec::with_capacity(items.len());
                    for item in items {
                        params.push(item);
                        placeholders.push(dialect.placeholder(*param_idx));
                        *param_idx += 1;
                    }
                    return format!("{} IN ({})", col, placeholders.join(", "));
                }
                CompareOp::IsNull => {
                    let want_null = !matches!(value, Value::Bool(false));
                    return if want_null {
                        format!("{} IS NULL", col)
                    } else {
                        format!("{} IS NOT NULL", col)
                    };
                }
                _ => {}
            }

            let (op_sql, bind_val) = match op {
                CompareOp::In | CompareOp::IsNull => unreachable!("handled above"),
                CompareOp::Ne => ("<>", value.clone()),
                CompareOp::Regex => ("~", value.clone()),
                CompareOp::IRegex => ("~*", value.clone()),
                CompareOp::IExact => (dialect.ilike(), value.clone()),
                CompareOp::Eq => ("=", value.clone()),
                CompareOp::Lt => ("<", value.clone()),
                CompareOp::Lte => ("<=", value.clone()),
                CompareOp::Gt => (">", value.clone()),
                CompareOp::Gte => (">=", value.clone()),
                CompareOp::Contains => {
                    let s = match value {
                        Value::Text(t) => format!("%{}%", t),
                        other => format!("%{}%", other),
                    };
                    ("LIKE", Value::Text(s))
                }
                CompareOp::IContains => {
                    let s = match value {
                        Value::Text(t) => format!("%{}%", t),
                        other => format!("%{}%", other),
                    };
                    (dialect.ilike(), Value::Text(s))
                }
                CompareOp::StartsWith => {
                    let s = match value {
                        Value::Text(t) => format!("{}%", t),
                        other => format!("{}%", other),
                    };
                    ("LIKE", Value::Text(s))
                }
                CompareOp::EndsWith => {
                    let s = match value {
                        Value::Text(t) => format!("%{}", t),
                        other => format!("%{}", other),
                    };
                    ("LIKE", Value::Text(s))
                }
            };
            params.push(bind_val);
            let placeholder = dialect.placeholder(*param_idx);
            *param_idx += 1;
            format!("{} {} {}", col, op_sql, placeholder)
        }
        Expr::And(exprs) => {
            if exprs.is_empty() {
                "TRUE".to_string()
            } else {
                let parts: Vec<String> = exprs
                    .iter()
                    .map(|e| {
                        format!(
                            "({})",
                            compile_expr_sql(e, field_to_col, params, param_idx, dialect)
                        )
                    })
                    .collect();
                parts.join(" AND ")
            }
        }
        Expr::Or(exprs) => {
            if exprs.is_empty() {
                "FALSE".to_string()
            } else {
                let parts: Vec<String> = exprs
                    .iter()
                    .map(|e| {
                        format!(
                            "({})",
                            compile_expr_sql(e, field_to_col, params, param_idx, dialect)
                        )
                    })
                    .collect();
                parts.join(" OR ")
            }
        }
        Expr::Not(inner) => {
            format!(
                "NOT ({})",
                compile_expr_sql(inner, field_to_col, params, param_idx, dialect)
            )
        }
        Expr::CompareField { left, op, right } => {
            let lhs = field_to_col(left);
            let rhs = field_to_col(right);
            let sql = match op {
                CompareOp::Eq => format!("{} = {}", lhs, rhs),
                CompareOp::Ne => format!("{} <> {}", lhs, rhs),
                CompareOp::Lt => format!("{} < {}", lhs, rhs),
                CompareOp::Lte => format!("{} <= {}", lhs, rhs),
                CompareOp::Gt => format!("{} > {}", lhs, rhs),
                CompareOp::Gte => format!("{} >= {}", lhs, rhs),
                CompareOp::Contains => format!("{} LIKE '%' || {} || '%'", lhs, rhs),
                CompareOp::IContains => {
                    format!("{} {} '%' || {} || '%'", lhs, dialect.ilike(), rhs)
                }
                CompareOp::StartsWith => format!("{} LIKE {} || '%'", lhs, rhs),
                CompareOp::EndsWith => format!("{} LIKE '%' || {}", lhs, rhs),
                CompareOp::IExact => format!("{} {} {}", lhs, dialect.ilike(), rhs),
                CompareOp::Regex => format!("{} ~ {}", lhs, rhs),
                CompareOp::IRegex => format!("{} ~* {}", lhs, rhs),
                CompareOp::In | CompareOp::IsNull => format!("{} = {}", lhs, rhs),
            };
            sql
        }
    }
}
