use crate::error::{FromRow, OrmError};
use crate::expr::{ArithOp, CompareOp, Expr, SetExpr, UnresolvedExpr, Value};
use crate::meta::{FieldKind, Model, ModelMeta};
use std::marker::PhantomData;

/// The SQL type a `Value::Null` must be bound as, so a NULL going into (say) a
/// TEXT or TIMESTAMPTZ column isn't sent typed as `int8` (sqlx/Postgres reject
/// a mismatched parameter type even for NULL). Every non-null `Value` variant
/// already carries its own type; only `Null` is ambiguous without this.
#[derive(Clone, Copy)]
enum NullBindKind {
    I64,
    F64,
    Text,
    Bool,
    DateTime,
}

/// Resolves the correct `NullBindKind` for a field on `meta` by name. Relation
/// (FK) fields aren't in `meta.fields` and are always bound as the related
/// row's `i64` id. `Decimal`/`Date`/`Time`/`Duration`/`Uuid` fall back to
/// `I64` — the derive macro (`crates/djangors-macros/src/model.rs`, the
/// "unsupported types for save/update operations" check) already rejects any
/// model with such a field at compile time, so no real `ModelMeta` in this
/// workspace can actually reach that arm; it exists only so this function
/// stays total instead of panicking on a hypothetical future field kind.
fn null_bind_kind_for(field_name: &str, meta: &'static ModelMeta) -> NullBindKind {
    match meta.fields.iter().find(|f| f.name == field_name) {
        Some(f) => match f.kind {
            FieldKind::Char
            | FieldKind::Text
            | FieldKind::Email
            | FieldKind::Url
            | FieldKind::Slug
            | FieldKind::Ip
            | FieldKind::FileField => NullBindKind::Text,
            FieldKind::Integer | FieldKind::BigInt => NullBindKind::I64,
            FieldKind::Float => NullBindKind::F64,
            FieldKind::Boolean => NullBindKind::Bool,
            FieldKind::DateTime => NullBindKind::DateTime,
            _ => NullBindKind::I64,
        },
        None => NullBindKind::I64,
    }
}

/// Lazily constructed database query builder for model `T`.
#[derive(Debug)]
pub struct QuerySet<T: Model + FromRow> {
    filters: Vec<Expr>,
    order_by: Vec<(String, bool)>, // (column, descending)
    limit: Option<i64>,
    offset: Option<i64>,
    _marker: PhantomData<T>,
}

impl<T: Model + FromRow> Clone for QuerySet<T> {
    fn clone(&self) -> Self {
        Self {
            filters: self.filters.clone(),
            order_by: self.order_by.clone(),
            limit: self.limit,
            offset: self.offset,
            _marker: PhantomData,
        }
    }
}

impl<T: Model + FromRow> Default for QuerySet<T> {
    fn default() -> Self {
        Self::new()
    }
}

impl<T: Model + FromRow> QuerySet<T> {
    /// Creates a new empty `QuerySet` for model `T`.
    pub fn new() -> Self {
        Self {
            filters: Vec::new(),
            order_by: Vec::new(),
            limit: None,
            offset: None,
            _marker: PhantomData,
        }
    }

    /// Adds filter expressions generated by `q!` to this queryset.
    ///
    /// Accepts a whole `Q`-style tree, so `OR` and `NOT` compose naturally:
    ///
    /// ```ignore
    /// qs.filter(q!(status = "open") | q!(status = "pending"))?
    ///   .filter(!q!(archived = true))?
    /// ```
    ///
    /// Successive `filter` calls are `AND`ed together, matching Django.
    pub fn filter(mut self, expr: UnresolvedExpr) -> Result<Self, OrmError> {
        let resolved = Self::resolve_expr(expr)?;
        self.filters.push(resolved);
        Ok(self)
    }

    /// The `SELECT` this queryset would execute, for debugging and tests —
    /// Django's `str(queryset.query)`.
    ///
    /// Placeholders are left as `$1`, `$2`, … rather than interpolated, so the
    /// output is never a runnable statement and can't be mistaken for one.
    pub fn debug_sql(&self) -> String {
        self.compile_select_with_order("*", true).0
    }

    /// The bind parameters [`debug_sql`](Self::debug_sql) would send, in order.
    pub fn debug_params(&self) -> Vec<Value> {
        self.compile_select_with_order("*", true).1
    }

    /// Excludes rows matching `expr` — the negation of [`filter`](Self::filter),
    /// equivalent to Django's `.exclude()`.
    pub fn exclude(mut self, expr: UnresolvedExpr) -> Result<Self, OrmError> {
        let resolved = Self::resolve_expr(expr)?;
        self.filters.push(Expr::Not(Box::new(resolved)));
        Ok(self)
    }

    /// Validates that `field` names a real field or relation on `T`, returning
    /// the name unchanged so callers can use it in a resolved [`Expr`].
    fn check_field(field: &'static str) -> Result<&'static str, OrmError> {
        let meta = T::meta();
        let exists = meta.fields.iter().any(|f| f.name == field)
            || meta.relations.iter().any(|r| r.field_name == field);
        if !exists {
            return Err(OrmError::FieldNotFound {
                field: field.to_string(),
                model: meta.struct_name,
            });
        }
        Ok(field)
    }

    /// Recursively resolves an [`UnresolvedExpr`] tree into an [`Expr`] tree,
    /// splitting lookup suffixes and validating every field name against `T`.
    fn resolve_expr(expr: UnresolvedExpr) -> Result<Expr, OrmError> {
        match expr {
            UnresolvedExpr::And(compares) => {
                let mut resolved = Vec::new();
                for comp in compares {
                    let (field_name, suffix) = split_field_lookup(comp.field);
                    let field = Self::check_field(field_name)?;
                    resolved.push(Expr::Compare {
                        field,
                        op: suffix_to_op(suffix),
                        value: comp.value,
                    });
                }
                Ok(Expr::And(resolved))
            }
            UnresolvedExpr::AndFields(compares) => {
                let mut resolved = Vec::new();
                for comp in compares {
                    let (left_name, suffix) = split_field_lookup(comp.left);
                    let left = Self::check_field(left_name)?;
                    let right = Self::check_field(comp.right)?;
                    resolved.push(Expr::CompareField {
                        left,
                        op: suffix_to_op(suffix),
                        right,
                    });
                }
                Ok(Expr::And(resolved))
            }
            UnresolvedExpr::All(nodes) => {
                let mut resolved = Vec::new();
                for node in nodes {
                    resolved.push(Self::resolve_expr(node)?);
                }
                Ok(Expr::And(resolved))
            }
            UnresolvedExpr::Any(nodes) => {
                let mut resolved = Vec::new();
                for node in nodes {
                    resolved.push(Self::resolve_expr(node)?);
                }
                Ok(Expr::Or(resolved))
            }
            UnresolvedExpr::Negate(inner) => Ok(Expr::Not(Box::new(Self::resolve_expr(*inner)?))),
        }
    }

    /// Groups by `group_by` and computes `aggs` per group — Django's
    /// `.values(...).annotate(...)`.
    ///
    /// Each returned [`GroupRow`] carries the group-key values and the named
    /// aggregate results, in the order requested. Any `ORDER BY` from the model
    /// or from [`order_by`](Self::order_by) is dropped, because ordering by a
    /// column that isn't in the `GROUP BY` is not valid SQL; order the returned
    /// rows in Rust instead.
    ///
    /// ```ignore
    /// let rows = Order::objects()
    ///     .filter(q!(status = "paid"))?
    ///     .annotate(&db, &["customer_id"], vec![("total", AggExpr::Sum { field: "amount" })])
    ///     .await?;
    /// ```
    pub async fn annotate<E: djangors_db::DbExecutor>(
        &self,
        mut db: E,
        group_by: &[&'static str],
        aggs: Vec<(&'static str, crate::aggregate::AggExpr)>,
    ) -> Result<Vec<GroupRow>, OrmError> {
        use sqlx::Row;

        let meta = T::meta();

        if group_by.is_empty() {
            return Err(OrmError::InvalidQuery(
                "annotate requires at least one group-by field".to_string(),
            ));
        }

        // Validate the group-by fields and every aggregate's field up front, so
        // a typo surfaces as FieldNotFound rather than a database syntax error.
        for field in group_by {
            Self::check_field(field)?;
        }
        for (_, agg) in &aggs {
            let field_name = agg_field(agg);
            if field_name != "*" {
                Self::check_field_named(field_name)?;
            }
        }

        let field_to_col = |field_name: &str| -> String {
            if let Some(f) = meta.fields.iter().find(|f| f.name == field_name) {
                format!("\"{}\"", f.column_name)
            } else if let Some(r) = meta.relations.iter().find(|r| r.field_name == field_name) {
                format!("\"{}\"", r.field_name)
            } else {
                field_name.to_string()
            }
        };

        let group_cols: Vec<String> = group_by.iter().map(|f| field_to_col(f)).collect();

        let mut select_parts = group_cols.clone();
        for (_, agg) in &aggs {
            select_parts.push(agg_sql(agg, &field_to_col));
        }

        let mut clean_qs = self.clone();
        clean_qs.limit = None;
        clean_qs.offset = None;
        let (mut sql, params) = clean_qs.compile_select_with_order(&select_parts.join(", "), false);
        sql.push_str(&format!(" GROUP BY {}", group_cols.join(", ")));

        let mut query = sqlx::query(sqlx::AssertSqlSafe(sql));
        for val in &params {
            query = bind_value(query, val);
        }

        db.record_query();
        let rows = db.conn().fetch_all(query).await?;

        let mut out = Vec::with_capacity(rows.len());
        for row in &rows {
            let mut keys = Vec::with_capacity(group_by.len());
            for (i, field) in group_by.iter().enumerate() {
                keys.push((*field, decode_value(row, i, field_kind_of(field, meta))));
            }

            let mut aggregates = Vec::with_capacity(aggs.len());
            for (i, (alias, agg)) in aggs.iter().enumerate() {
                let idx = group_by.len() + i;
                let res = match agg {
                    crate::aggregate::AggExpr::Count { .. } => row
                        .try_get::<Option<i64>, _>(idx)
                        .ok()
                        .flatten()
                        .map(crate::aggregate::AggResult::I64)
                        .unwrap_or(crate::aggregate::AggResult::Null),
                    _ => row
                        .try_get::<Option<f64>, _>(idx)
                        .ok()
                        .flatten()
                        .map(crate::aggregate::AggResult::F64)
                        .unwrap_or(crate::aggregate::AggResult::Null),
                };
                aggregates.push(((*alias).to_string(), res));
            }

            out.push(GroupRow { keys, aggregates });
        }

        Ok(out)
    }

    /// Selects only `fields`, returning raw column values rather than model
    /// instances — Django's `.values()`.
    ///
    /// Useful when a model has columns you don't want to pay to fetch, or when
    /// feeding a serializer that only needs a projection.
    pub async fn values<E: djangors_db::DbExecutor>(
        &self,
        mut db: E,
        fields: &[&'static str],
    ) -> Result<Vec<Vec<(&'static str, Value)>>, OrmError> {
        let meta = T::meta();

        if fields.is_empty() {
            return Err(OrmError::InvalidQuery(
                "values requires at least one field".to_string(),
            ));
        }
        for field in fields {
            Self::check_field(field)?;
        }

        let select_list = fields
            .iter()
            .map(|f| {
                if let Some(fm) = meta.fields.iter().find(|m| m.name == *f) {
                    format!("\"{}\"", fm.column_name)
                } else {
                    format!("\"{}\"", f)
                }
            })
            .collect::<Vec<_>>()
            .join(", ");

        let (sql, params) = self.compile_select_with_order(&select_list, true);

        let mut query = sqlx::query(sqlx::AssertSqlSafe(sql));
        for val in &params {
            query = bind_value(query, val);
        }

        db.record_query();
        let rows = db.conn().fetch_all(query).await?;

        Ok(rows
            .iter()
            .map(|row| {
                fields
                    .iter()
                    .enumerate()
                    .map(|(i, f)| (*f, decode_value(row, i, field_kind_of(f, meta))))
                    .collect()
            })
            .collect())
    }

    /// Like [`values`](Self::values) but for a single field, returning a flat
    /// column of values — Django's `.values_list(field, flat=True)`.
    pub async fn values_list<E: djangors_db::DbExecutor>(
        &self,
        db: E,
        field: &'static str,
    ) -> Result<Vec<Value>, OrmError> {
        let rows = self.values(db, &[field]).await?;
        Ok(rows
            .into_iter()
            .filter_map(|mut r| r.pop().map(|(_, v)| v))
            .collect())
    }

    /// Field-name validation for a non-`'static` name (used by aggregates).
    fn check_field_named(field: &str) -> Result<(), OrmError> {
        let meta = T::meta();
        let exists = meta.fields.iter().any(|f| f.name == field)
            || meta.relations.iter().any(|r| r.field_name == field);
        if !exists {
            return Err(OrmError::FieldNotFound {
                field: field.to_string(),
                model: meta.struct_name,
            });
        }
        Ok(())
    }

    /// ILIKE-matches `term` against every field in `fields`, OR'd together, ANDed
    /// with any other filters already applied. Every name in `fields` must be a
    /// real field on `T` (relations are not searchable this way — no `field_to_col`
    /// mapping ambiguity to worry about since relation values aren't text).
    pub fn filter_or_icontains(
        mut self,
        fields: &[&'static str],
        term: &str,
    ) -> Result<Self, OrmError> {
        let meta = T::meta();
        let mut compares = Vec::new();
        for field_name in fields {
            if !meta.fields.iter().any(|f| f.name == *field_name) {
                return Err(OrmError::FieldNotFound {
                    field: field_name.to_string(),
                    model: meta.struct_name,
                });
            }
            compares.push(Expr::Compare {
                field: field_name,
                op: CompareOp::IContains,
                value: Value::Text(term.to_string()),
            });
        }
        self.filters.push(Expr::Or(compares));
        Ok(self)
    }

    /// Restricts to rows where `field` (a real DateTime field on `T`) is in
    /// `[gte, lt)`. Half-open on purpose: `lt` is the exclusive upper bound, so
    /// callers pass "start of next unit" rather than doing inclusive-end math
    /// against a field that also carries a time-of-day component.
    pub fn filter_datetime_range(
        mut self,
        field: &'static str,
        gte: chrono::DateTime<chrono::Utc>,
        lt: chrono::DateTime<chrono::Utc>,
    ) -> Result<Self, OrmError> {
        let meta = T::meta();
        if !meta.fields.iter().any(|f| f.name == field) {
            return Err(OrmError::FieldNotFound {
                field: field.to_string(),
                model: meta.struct_name,
            });
        }
        self.filters.push(Expr::And(vec![
            Expr::Compare {
                field,
                op: CompareOp::Gte,
                value: Value::DateTime(gte),
            },
            Expr::Compare {
                field,
                op: CompareOp::Lt,
                value: Value::DateTime(lt),
            },
        ]));
        Ok(self)
    }

    /// Restricts results to rows strictly after a keyset position.
    pub fn after(
        mut self,
        order_field: &'static str,
        order_value: Value,
        pk_field: &'static str,
        cursor_pk: i64,
        descending: bool,
    ) -> Result<Self, OrmError> {
        let meta = T::meta();
        for field in [order_field, pk_field] {
            if !meta.fields.iter().any(|f| f.name == field)
                && !meta.relations.iter().any(|r| r.field_name == field)
            {
                return Err(OrmError::FieldNotFound {
                    field: field.to_string(),
                    model: meta.struct_name,
                });
            }
        }
        let op = if descending {
            CompareOp::Lt
        } else {
            CompareOp::Gt
        };
        self.filters.push(Expr::Or(vec![
            Expr::Compare {
                field: order_field,
                op,
                value: order_value.clone(),
            },
            Expr::And(vec![
                Expr::Compare {
                    field: order_field,
                    op: CompareOp::Eq,
                    value: order_value,
                },
                Expr::Compare {
                    field: pk_field,
                    op,
                    value: Value::I64(cursor_pk),
                },
            ]),
        ]));
        Ok(self)
    }

    /// Order results by the given field. A leading `-` means descending.
    ///
    /// # Errors
    /// Returns [`OrmError::FieldNotFound`] if `field` does not match any field
    /// or relation on `T`. This validation exists specifically so a caller can
    /// never get an unvalidated string interpolated into the generated SQL's
    /// `ORDER BY` clause — column/table identifiers can't be bound as query
    /// parameters the way values can, so rejecting anything that isn't a known
    /// column name (from `T::meta()`, not caller input) is the only safe
    /// mitigation against SQL injection via this method.
    pub fn order_by(mut self, field: &str) -> Result<Self, OrmError> {
        let (clean_field, desc) = if let Some(stripped) = field.strip_prefix('-') {
            (stripped, true)
        } else {
            (field, false)
        };
        let meta = T::meta();
        let col = if let Some(f) = meta.fields.iter().find(|f| f.name == clean_field) {
            format!("\"{}\"", f.column_name)
        } else if let Some(r) = meta.relations.iter().find(|r| r.field_name == clean_field) {
            format!("\"{}\"", r.field_name)
        } else {
            return Err(OrmError::FieldNotFound {
                field: clean_field.to_string(),
                model: meta.struct_name,
            });
        };
        self.order_by.push((col, desc));
        Ok(self)
    }

    /// Restricts the maximum number of rows returned by the query.
    pub fn limit(mut self, n: i64) -> Self {
        self.limit = Some(n);
        self
    }

    /// Sets the number of rows to skip before starting to return rows.
    pub fn offset(mut self, n: i64) -> Self {
        self.offset = Some(n);
        self
    }

    /// Compiles the query to a `SELECT *` SQL string and parameter list.
    pub fn compile_select(&self) -> (String, Vec<Value>) {
        self.compile_select_custom("*")
    }

    /// Compiles the query to a SQL string selecting `select_list` columns and parameter list.
    pub fn compile_select_custom(&self, select_list: &str) -> (String, Vec<Value>) {
        self.compile_select_with_order(select_list, true)
    }

    /// `include_order: false` is for aggregate-shaped selects (COUNT,
    /// SUM, ...): Postgres rejects `SELECT COUNT(*) ... ORDER BY col`
    /// ("must appear in the GROUP BY clause"), and clearing `order_by`
    /// on a cloned queryset is not enough because an empty `order_by`
    /// falls back to `meta.ordering` below.
    pub(crate) fn compile_select_with_order(
        &self,
        select_list: &str,
        include_order: bool,
    ) -> (String, Vec<Value>) {
        let meta = T::meta();
        let mut sql = format!("SELECT {} FROM \"{}\"", select_list, meta.table_name);
        let mut params = Vec::new();
        let mut param_idx = 1;

        let field_to_col = |field_name: &str| -> String {
            if let Some(f) = meta.fields.iter().find(|f| f.name == field_name) {
                format!("\"{}\"", f.column_name)
            } else if let Some(r) = meta.relations.iter().find(|r| r.field_name == field_name) {
                format!("\"{}\"", r.field_name)
            } else {
                field_name.to_string()
            }
        };

        if !self.filters.is_empty() {
            let combined = Expr::And(self.filters.clone());
            let where_clause =
                compile_expr_sql(&combined, &field_to_col, &mut params, &mut param_idx);
            sql.push_str(" WHERE ");
            sql.push_str(&where_clause);
        }

        let order_source = if !include_order {
            Vec::new()
        } else if !self.order_by.is_empty() {
            self.order_by.clone()
        } else {
            meta.ordering
                .iter()
                .map(|&field| {
                    let (clean_field, desc) = if let Some(stripped) = field.strip_prefix('-') {
                        (stripped, true)
                    } else {
                        (field, false)
                    };
                    let col = if let Some(f) = meta.fields.iter().find(|f| f.name == clean_field) {
                        format!("\"{}\"", f.column_name)
                    } else if let Some(r) =
                        meta.relations.iter().find(|r| r.field_name == clean_field)
                    {
                        format!("\"{}\"", r.field_name)
                    } else {
                        clean_field.to_string()
                    };
                    (col, desc)
                })
                .collect()
        };

        if !order_source.is_empty() {
            let order_parts: Vec<String> = order_source
                .iter()
                .map(|(col, desc)| {
                    if *desc {
                        format!("{} DESC", col)
                    } else {
                        format!("{} ASC", col)
                    }
                })
                .collect();
            sql.push_str(" ORDER BY ");
            sql.push_str(&order_parts.join(", "));
        }

        if let Some(limit) = self.limit {
            sql.push_str(&format!(" LIMIT {}", limit));
        }
        if let Some(offset) = self.offset {
            sql.push_str(&format!(" OFFSET {}", offset));
        }

        (sql, params)
    }

    /// Executes the query and returns all matching model instances.
    pub async fn all<E: djangors_db::DbExecutor>(&self, mut db: E) -> Result<Vec<T>, OrmError> {
        let (sql, params) = self.compile_select();
        let mut query = sqlx::query(sqlx::AssertSqlSafe(sql));
        for val in &params {
            query = match val {
                Value::I64(v) => query.bind(*v),
                Value::F64(v) => query.bind(*v),
                Value::Text(v) => query.bind(v.clone()),
                Value::Bool(v) => query.bind(*v),
                Value::DateTime(v) => query.bind(*v),
                Value::Null => query.bind(None::<i64>),
                // A list only ever appears as the right-hand side of an
                // `__in` lookup, which `compile_expr_sql` expands into one
                // placeholder per element before binding ever happens. Binding
                // NULL keeps this match total without inventing a wire format.
                Value::List(_) => query.bind(None::<i64>),
            };
        }
        db.record_query();
        let rows = db.conn().fetch_all(query).await?;
        let mut results = Vec::new();
        for row in rows {
            results.push(T::from_row(&row)?);
        }
        Ok(results)
    }

    /// Fetches a single model instance matching the query filters.
    /// Returns `OrmError::NotFound` if no row matches, or `OrmError::MultipleObjectsReturned` if more than one row matches.
    pub async fn get<E: djangors_db::DbExecutor>(&self, db: E) -> Result<T, OrmError> {
        let mut cloned = self.clone();
        cloned.limit = Some(2);
        let results = cloned.all(db).await?;
        if results.is_empty() {
            Err(OrmError::NotFound {
                model: T::meta().struct_name,
            })
        } else if results.len() > 1 {
            Err(OrmError::MultipleObjectsReturned {
                model: T::meta().struct_name,
            })
        } else {
            Ok(results.into_iter().next().unwrap())
        }
    }

    /// Fetches the first model instance matching the query filters, or `None` if no row matches.
    pub async fn first<E: djangors_db::DbExecutor>(&self, db: E) -> Result<Option<T>, OrmError> {
        let mut cloned = self.clone();
        cloned.limit = Some(1);
        let results = cloned.all(db).await?;
        Ok(results.into_iter().next())
    }

    /// Returns `true` if at least one record matches the query filters.
    pub async fn exists<E: djangors_db::DbExecutor>(&self, mut db: E) -> Result<bool, OrmError> {
        let mut cloned = self.clone();
        cloned.limit = Some(1);
        let (sql, params) = cloned.compile_select_with_order("1", false);
        let mut query = sqlx::query(sqlx::AssertSqlSafe(sql));
        for val in &params {
            query = match val {
                Value::I64(v) => query.bind(*v),
                Value::F64(v) => query.bind(*v),
                Value::Text(v) => query.bind(v.clone()),
                Value::Bool(v) => query.bind(*v),
                Value::DateTime(v) => query.bind(*v),
                Value::Null => query.bind(None::<i64>),
                // A list only ever appears as the right-hand side of an
                // `__in` lookup, which `compile_expr_sql` expands into one
                // placeholder per element before binding ever happens. Binding
                // NULL keeps this match total without inventing a wire format.
                Value::List(_) => query.bind(None::<i64>),
            };
        }
        db.record_query();
        let row_opt = db.conn().fetch_optional(query).await?;
        Ok(row_opt.is_some())
    }

    /// Returns the total count of rows matching the query filters.
    pub async fn count<E: djangors_db::DbExecutor>(&self, mut db: E) -> Result<i64, OrmError> {
        let (sql, params) = self.compile_select_with_order("COUNT(*)", false);
        let mut query = sqlx::query(sqlx::AssertSqlSafe(sql));
        for val in &params {
            query = match val {
                Value::I64(v) => query.bind(*v),
                Value::F64(v) => query.bind(*v),
                Value::Text(v) => query.bind(v.clone()),
                Value::Bool(v) => query.bind(*v),
                Value::DateTime(v) => query.bind(*v),
                Value::Null => query.bind(None::<i64>),
                // A list only ever appears as the right-hand side of an
                // `__in` lookup, which `compile_expr_sql` expands into one
                // placeholder per element before binding ever happens. Binding
                // NULL keeps this match total without inventing a wire format.
                Value::List(_) => query.bind(None::<i64>),
            };
        }
        db.record_query();
        let row = db.conn().fetch_one(query).await?;
        use sqlx::Row;
        let count: i64 = row.try_get(0)?;
        Ok(count)
    }

    /// Executes aggregate functions over matching rows.
    pub async fn aggregate<E: djangors_db::DbExecutor>(
        &self,
        mut db: E,
        aggs: Vec<crate::aggregate::AggExpr>,
    ) -> Result<Vec<crate::aggregate::AggResult>, OrmError> {
        let meta = T::meta();

        // 1. Validate every AggExpr's field (except Count's "*" sentinel) against T::meta().fields
        for agg in &aggs {
            let field_name = match agg {
                crate::aggregate::AggExpr::Count { field } => *field,
                crate::aggregate::AggExpr::Sum { field } => *field,
                crate::aggregate::AggExpr::Avg { field } => *field,
                crate::aggregate::AggExpr::Min { field } => *field,
                crate::aggregate::AggExpr::Max { field } => *field,
            };

            if field_name != "*" {
                let exists = meta.fields.iter().any(|f| f.name == field_name)
                    || meta.relations.iter().any(|r| r.field_name == field_name);
                if !exists {
                    return Err(OrmError::FieldNotFound {
                        field: field_name.to_string(),
                        model: meta.struct_name,
                    });
                }
            }
        }

        // 2. Build SELECT list and custom SQL.
        let field_to_col = |field_name: &str| -> String {
            if let Some(f) = meta.fields.iter().find(|f| f.name == field_name) {
                format!("\"{}\"", f.column_name)
            } else if let Some(r) = meta.relations.iter().find(|r| r.field_name == field_name) {
                format!("\"{}\"", r.field_name)
            } else {
                field_name.to_string()
            }
        };

        let mut agg_sql_parts = Vec::new();
        for agg in &aggs {
            let part = match agg {
                crate::aggregate::AggExpr::Count { field } => {
                    if *field == "*" {
                        "COUNT(*)".to_string()
                    } else {
                        format!("COUNT({})", field_to_col(field))
                    }
                }
                // Cast to float8 so the result is always decodable as
                // Option<f64> client-side, regardless of the underlying
                // column's numeric type. Without this, Postgres returns
                // different native types depending on both the aggregate
                // function and the column type — SUM(integer) -> bigint,
                // SUM(bigint)/AVG(integer|bigint) -> numeric, MIN/MAX(real)
                // -> double precision, etc. Casting in SQL sidesteps having
                // to handle every combination on the Rust side.
                crate::aggregate::AggExpr::Sum { field } => {
                    format!("SUM({})::float8", field_to_col(field))
                }
                crate::aggregate::AggExpr::Avg { field } => {
                    format!("AVG({})::float8", field_to_col(field))
                }
                crate::aggregate::AggExpr::Min { field } => {
                    format!("MIN({})::float8", field_to_col(field))
                }
                crate::aggregate::AggExpr::Max { field } => {
                    format!("MAX({})::float8", field_to_col(field))
                }
            };
            agg_sql_parts.push(part);
        }

        let select_list = agg_sql_parts.join(", ");

        // A single aggregate row has nothing to order or paginate — reuse
        // the shared compilation (so the WHERE clause stays in sync with
        // the regular filter-compilation path) with ordering excluded
        // (clearing `order_by` alone would fall back to `meta.ordering`)
        // and limit/offset cleared on a clone.
        let mut clean_qs = self.clone();
        clean_qs.limit = None;
        clean_qs.offset = None;

        let (sql, params) = clean_qs.compile_select_with_order(&select_list, false);

        let mut query = sqlx::query(sqlx::AssertSqlSafe(sql));
        for val in &params {
            query = match val {
                Value::I64(v) => query.bind(*v),
                Value::F64(v) => query.bind(*v),
                Value::Text(v) => query.bind(v.clone()),
                Value::Bool(v) => query.bind(*v),
                Value::DateTime(v) => query.bind(*v),
                Value::Null => query.bind(None::<i64>),
                // A list only ever appears as the right-hand side of an
                // `__in` lookup, which `compile_expr_sql` expands into one
                // placeholder per element before binding ever happens. Binding
                // NULL keeps this match total without inventing a wire format.
                Value::List(_) => query.bind(None::<i64>),
            };
        }

        db.record_query();
        let row = db.conn().fetch_one(query).await?;
        use sqlx::Row;

        let mut results = Vec::new();
        for (i, agg) in aggs.iter().enumerate() {
            let res = match agg {
                crate::aggregate::AggExpr::Count { .. } => {
                    let count_val: i64 = row.try_get(i)?;
                    crate::aggregate::AggResult::I64(count_val)
                }
                crate::aggregate::AggExpr::Sum { .. }
                | crate::aggregate::AggExpr::Avg { .. }
                | crate::aggregate::AggExpr::Min { .. }
                | crate::aggregate::AggExpr::Max { .. } => {
                    let val: Option<f64> = row.try_get(i)?;
                    match val {
                        Some(v) => crate::aggregate::AggResult::F64(v),
                        None => crate::aggregate::AggResult::Null,
                    }
                }
            };
            results.push(res);
        }

        Ok(results)
    }

    /// Executes a bulk UPDATE query matching current filters with specified field set expressions.
    pub async fn update<E: djangors_db::DbExecutor>(
        &self,
        mut db: E,
        sets: Vec<(&'static str, SetExpr)>,
    ) -> Result<u64, OrmError> {
        let meta = T::meta();

        // 1. Validate every field name in `sets` (LHS and RHS F-expressions if any)
        for &(field_name, ref set_expr) in &sets {
            let exists_lhs = meta.fields.iter().any(|f| f.name == field_name)
                || meta.relations.iter().any(|r| r.field_name == field_name);
            if !exists_lhs {
                return Err(OrmError::FieldNotFound {
                    field: field_name.to_string(),
                    model: meta.struct_name,
                });
            }

            if let SetExpr::FieldOp {
                field: rhs_field, ..
            } = set_expr
            {
                let exists_rhs = meta.fields.iter().any(|f| f.name == *rhs_field)
                    || meta.relations.iter().any(|r| r.field_name == *rhs_field);
                if !exists_rhs {
                    return Err(OrmError::FieldNotFound {
                        field: rhs_field.to_string(),
                        model: meta.struct_name,
                    });
                }
            }
        }

        // 2. Build the UPDATE SQL statement
        let field_to_col = |field_name: &str| -> String {
            if let Some(f) = meta.fields.iter().find(|f| f.name == field_name) {
                format!("\"{}\"", f.column_name)
            } else if let Some(r) = meta.relations.iter().find(|r| r.field_name == field_name) {
                format!("\"{}\"", r.field_name)
            } else {
                field_name.to_string()
            }
        };

        let mut params = Vec::new();
        // Parallel to `params`: the correct bind type for a `Value::Null` at
        // that index. SET-clause entries get a real field-derived kind below;
        // WHERE-clause entries appended by `compile_expr_sql` (which has no
        // per-value field context) default to `I64`, matching this
        // function's pre-existing behavior for filter values.
        let mut null_kinds = Vec::new();
        let mut param_idx = 1;
        let mut set_parts = Vec::new();

        for &(field_name, ref set_expr) in &sets {
            let lhs_col = field_to_col(field_name);
            match set_expr {
                SetExpr::Literal(v) => {
                    set_parts.push(format!("{} = ${}", lhs_col, param_idx));
                    params.push(v.clone());
                    null_kinds.push(null_bind_kind_for(field_name, meta));
                    param_idx += 1;
                }
                SetExpr::FieldOp { field, op, operand } => {
                    let rhs_col = field_to_col(field);
                    let op_sql = match op {
                        ArithOp::Add => "+",
                        ArithOp::Sub => "-",
                        ArithOp::Mul => "*",
                        ArithOp::Div => "/",
                    };
                    set_parts.push(format!(
                        "{} = {} {} ${}",
                        lhs_col, rhs_col, op_sql, param_idx
                    ));
                    params.push(operand.clone());
                    null_kinds.push(null_bind_kind_for(field_name, meta));
                    param_idx += 1;
                }
            }
        }

        let mut sql = format!(
            "UPDATE \"{}\" SET {}",
            meta.table_name,
            set_parts.join(", ")
        );
        if !self.filters.is_empty() {
            let combined = Expr::And(self.filters.clone());
            let where_clause =
                compile_expr_sql(&combined, &field_to_col, &mut params, &mut param_idx);
            null_kinds.resize(params.len(), NullBindKind::I64);
            sql.push_str(" WHERE ");
            sql.push_str(&where_clause);
        }

        let mut query = sqlx::query(sqlx::AssertSqlSafe(sql));
        for (i, val) in params.iter().enumerate() {
            query = match val {
                Value::I64(v) => query.bind(*v),
                Value::F64(v) => query.bind(*v),
                Value::Text(v) => query.bind(v.clone()),
                Value::Bool(v) => query.bind(*v),
                Value::DateTime(v) => query.bind(*v),
                Value::Null => match null_kinds[i] {
                    NullBindKind::I64 => query.bind(None::<i64>),
                    NullBindKind::F64 => query.bind(None::<f64>),
                    NullBindKind::Text => query.bind(None::<String>),
                    NullBindKind::Bool => query.bind(None::<bool>),
                    NullBindKind::DateTime => query.bind(None::<chrono::DateTime<chrono::Utc>>),
                },
                // A list only ever appears as the right-hand side of an
                // `__in` lookup, which `compile_expr_sql` expands into one
                // placeholder per element before binding ever happens. Binding
                // NULL keeps this match total without inventing a wire format.
                Value::List(_) => query.bind(None::<i64>),
            };
        }

        db.record_query();
        let res = db.conn().execute(query).await?;
        Ok(res.rows_affected())
    }

    /// Performs a low-level INSERT query for `T` returning the generated primary key ID.
    pub async fn insert_raw<E: djangors_db::DbExecutor>(
        mut db: E,
        values: Vec<(&'static str, crate::expr::Value)>,
    ) -> Result<i64, OrmError> {
        let meta = T::meta();
        let pk_field = meta
            .fields
            .iter()
            .find(|f| f.primary_key)
            .expect("Primary key field not found");
        let pk_column = pk_field.column_name;

        let mut processed_values = Vec::new();
        for (field_name, val) in values {
            if let Some(f) = meta.fields.iter().find(|f| f.name == field_name) {
                if f.auto {
                    continue;
                }
                processed_values.push((f.column_name, val, field_name));
            } else if let Some(r) = meta.relations.iter().find(|r| r.field_name == field_name) {
                processed_values.push((r.field_name, val, field_name));
            } else {
                return Err(OrmError::FieldNotFound {
                    field: field_name.to_string(),
                    model: meta.struct_name,
                });
            }
        }

        let mut cols = Vec::new();
        let mut placeholders = Vec::new();
        let mut params = Vec::new();
        let mut null_kinds = Vec::new();
        for (i, (col_name, val, field_name)) in processed_values.into_iter().enumerate() {
            cols.push(format!("\"{}\"", col_name));
            placeholders.push(format!("${}", i + 1));
            null_kinds.push(null_bind_kind_for(field_name, meta));
            params.push(val);
        }

        let sql = if cols.is_empty() {
            format!(
                "INSERT INTO \"{}\" DEFAULT VALUES RETURNING \"{}\"",
                meta.table_name, pk_column
            )
        } else {
            format!(
                "INSERT INTO \"{}\" ({}) VALUES ({}) RETURNING \"{}\"",
                meta.table_name,
                cols.join(", "),
                placeholders.join(", "),
                pk_column
            )
        };

        let mut query = sqlx::query(sqlx::AssertSqlSafe(sql));
        for (i, val) in params.iter().enumerate() {
            query = match val {
                Value::I64(v) => query.bind(*v),
                Value::F64(v) => query.bind(*v),
                Value::Text(v) => query.bind(v.clone()),
                Value::Bool(v) => query.bind(*v),
                Value::DateTime(v) => query.bind(*v),
                Value::Null => match null_kinds[i] {
                    NullBindKind::I64 => query.bind(None::<i64>),
                    NullBindKind::F64 => query.bind(None::<f64>),
                    NullBindKind::Text => query.bind(None::<String>),
                    NullBindKind::Bool => query.bind(None::<bool>),
                    NullBindKind::DateTime => query.bind(None::<chrono::DateTime<chrono::Utc>>),
                },
                // A list only ever appears as the right-hand side of an
                // `__in` lookup, which `compile_expr_sql` expands into one
                // placeholder per element before binding ever happens. Binding
                // NULL keeps this match total without inventing a wire format.
                Value::List(_) => query.bind(None::<i64>),
            };
        }

        use sqlx::Row;
        db.record_query();
        let row = db.conn().fetch_one(query).await?;
        let pk: i64 = row.try_get(0)?;
        Ok(pk)
    }

    /// Inserts every item in `items` in a single multi-row `INSERT` statement, returning the
    /// generated primary key for each row in the same order as `items`. Auto (e.g.
    /// `#[djangors(auto)]`) fields are skipped on every row, same as [`Self::insert_raw`].
    /// Empty input is a no-op returning an empty `Vec` (no query is issued).
    pub async fn bulk_create<E: djangors_db::DbExecutor>(
        mut db: E,
        items: &[T],
    ) -> Result<Vec<i64>, OrmError>
    where
        T: Model,
    {
        if items.is_empty() {
            return Ok(Vec::new());
        }

        let meta = T::meta();
        let pk_field = meta
            .fields
            .iter()
            .find(|f| f.primary_key)
            .expect("Primary key field not found");
        let pk_column = pk_field.column_name;

        // Column order is taken from the first row and every subsequent row is bound in that
        // same order - safe because every item is the same `T`, so `field_values()` always
        // returns the same field set in the same declaration order for every row.
        let is_insertable = |field_name: &str| -> bool {
            match meta.fields.iter().find(|f| f.name == field_name) {
                Some(f) => !f.auto,
                None => meta.relations.iter().any(|r| r.field_name == field_name),
            }
        };

        let mut cols: Vec<String> = Vec::new();
        let mut col_order: Vec<&'static str> = Vec::new();
        for (field_name, _) in items[0].field_values() {
            if is_insertable(field_name) {
                let col_name = match meta.fields.iter().find(|f| f.name == field_name) {
                    Some(f) => f.column_name,
                    None => field_name,
                };
                cols.push(format!("\"{col_name}\""));
                col_order.push(field_name);
            }
        }

        let mut placeholder_groups = Vec::new();
        let mut params = Vec::new();
        let mut null_kinds = Vec::new();
        let mut param_idx = 1;
        for item in items {
            let values = item.field_values();
            let mut row_placeholders = Vec::new();
            for field_name in &col_order {
                let val = values
                    .iter()
                    .find(|(name, _)| name == field_name)
                    .map(|(_, v)| v.clone())
                    .unwrap_or(Value::Null);
                row_placeholders.push(format!("${param_idx}"));
                null_kinds.push(null_bind_kind_for(field_name, meta));
                params.push(val);
                param_idx += 1;
            }
            placeholder_groups.push(format!("({})", row_placeholders.join(", ")));
        }

        let sql = format!(
            "INSERT INTO \"{}\" ({}) VALUES {} RETURNING \"{}\"",
            meta.table_name,
            cols.join(", "),
            placeholder_groups.join(", "),
            pk_column
        );

        let mut query = sqlx::query(sqlx::AssertSqlSafe(sql));
        for (i, val) in params.iter().enumerate() {
            query = match val {
                Value::I64(v) => query.bind(*v),
                Value::F64(v) => query.bind(*v),
                Value::Text(v) => query.bind(v.clone()),
                Value::Bool(v) => query.bind(*v),
                Value::DateTime(v) => query.bind(*v),
                Value::Null => match null_kinds[i] {
                    NullBindKind::I64 => query.bind(None::<i64>),
                    NullBindKind::F64 => query.bind(None::<f64>),
                    NullBindKind::Text => query.bind(None::<String>),
                    NullBindKind::Bool => query.bind(None::<bool>),
                    NullBindKind::DateTime => query.bind(None::<chrono::DateTime<chrono::Utc>>),
                },
                // A list only ever appears as the right-hand side of an
                // `__in` lookup, which `compile_expr_sql` expands into one
                // placeholder per element before binding ever happens. Binding
                // NULL keeps this match total without inventing a wire format.
                Value::List(_) => query.bind(None::<i64>),
            };
        }

        use sqlx::Row;
        db.record_query();
        let rows = db.conn().fetch_all(query).await?;
        rows.iter().map(|row| Ok(row.try_get(0)?)).collect()
    }

    /// Deletes a record from table `T` by primary key `pk`.
    pub async fn delete_by_pk<E: djangors_db::DbExecutor>(
        mut db: E,
        pk: i64,
    ) -> Result<u64, OrmError> {
        let meta = T::meta();
        let pk_field = meta
            .fields
            .iter()
            .find(|f| f.primary_key)
            .expect("Primary key field not found");

        let sql = format!(
            "DELETE FROM \"{}\" WHERE \"{}\" = $1",
            meta.table_name, pk_field.column_name
        );
        db.record_query();
        let res = db
            .conn()
            .execute(sqlx::query(sqlx::AssertSqlSafe(sql)).bind(pk))
            .await
            .map_err(OrmError::from)?;
        Ok(res.rows_affected())
    }

    /// Eagerly loads the given relation, avoiding an N+1 query. Returns each
    /// matching `T` alongside its related `R` (or `None` if the relation is
    /// nullable and actually null for that row).
    pub async fn select_related<R: Model + FromRow + Clone, E: djangors_db::DbExecutor>(
        &self,
        mut db: E,
        relation_field: &'static str,
    ) -> Result<Vec<(T, Option<R>)>, OrmError> {
        let meta = T::meta();

        // 1. Validate relation_field exists in T::meta().relations
        let relation = meta
            .relations
            .iter()
            .find(|r| r.field_name == relation_field)
            .ok_or_else(|| OrmError::FieldNotFound {
                field: relation_field.to_string(),
                model: meta.struct_name,
            })?;

        // Validate that R matches the target of the relation
        let target_meta = (relation.target)();
        let r_meta = R::meta();
        if target_meta.struct_name != r_meta.struct_name {
            return Err(OrmError::FieldNotFound {
                field: format!(
                    "{} (target model mismatch: expected {}, found {})",
                    relation_field, r_meta.struct_name, target_meta.struct_name
                ),
                model: meta.struct_name,
            });
        }

        // 2 & 3. Run T's query and select the relation's raw FK column explicitly
        let select_list = format!("*, {} AS __select_related_fk", relation_field);
        let (sql, params) = self.compile_select_custom(&select_list);

        let mut query = sqlx::query(sqlx::AssertSqlSafe(sql));
        for val in &params {
            query = match val {
                Value::I64(v) => query.bind(*v),
                Value::F64(v) => query.bind(*v),
                Value::Text(v) => query.bind(v.clone()),
                Value::Bool(v) => query.bind(*v),
                Value::DateTime(v) => query.bind(*v),
                Value::Null => query.bind(None::<i64>),
                // A list only ever appears as the right-hand side of an
                // `__in` lookup, which `compile_expr_sql` expands into one
                // placeholder per element before binding ever happens. Binding
                // NULL keeps this match total without inventing a wire format.
                Value::List(_) => query.bind(None::<i64>),
            };
        }
        db.record_query();
        let rows = db.conn().fetch_all(query).await?;

        // 4. Collect distinct non-null ids and map T records
        let mut t_records = Vec::new();
        let mut relation_ids = std::collections::HashSet::new();

        for row in rows {
            let t = T::from_row(&row)?;
            use sqlx::Row;
            let fk_id: Option<i64> = row.try_get("__select_related_fk")?;
            if let Some(id) = fk_id {
                relation_ids.insert(id);
            }
            t_records.push((t, fk_id));
        }

        if relation_ids.is_empty() {
            return Ok(t_records.into_iter().map(|(t, _)| (t, None)).collect());
        }

        // 5. Run ONE query for related records
        let r_pk_field = r_meta
            .fields
            .iter()
            .find(|f| f.primary_key)
            .ok_or_else(|| OrmError::FieldNotFound {
                field: "primary_key".to_string(),
                model: r_meta.struct_name,
            })?;
        let r_pk_col = r_pk_field.column_name;

        let r_sql = format!(
            "SELECT * FROM \"{}\" WHERE \"{}\" = ANY($1)",
            r_meta.table_name, r_pk_col
        );

        let relation_ids_vec: Vec<i64> = relation_ids.into_iter().collect();
        let mut r_query = sqlx::query(sqlx::AssertSqlSafe(r_sql));
        r_query = r_query.bind(relation_ids_vec);

        db.record_query();
        let r_rows = db.conn().fetch_all(r_query).await?;

        let mut r_map = std::collections::HashMap::new();
        for r_row in r_rows {
            let r = R::from_row(&r_row)?;
            use sqlx::Row;
            let pk_val: i64 = r_row.try_get(r_pk_col)?;
            r_map.insert(pk_val, r);
        }

        // 6. Zip T records with R records
        let mut final_results = Vec::new();
        for (t, fk_id_opt) in t_records {
            let r_opt = match fk_id_opt {
                Some(id) => r_map.get(&id).cloned(),
                None => None,
            };
            final_results.push((t, r_opt));
        }

        Ok(final_results)
    }
}

/// Batch-loads the reverse side of a foreign-key relation for already-fetched
/// parents. The returned map omits parents with no matching children.
pub async fn prefetch_related<T, R, E>(
    mut db: E,
    parents: &[T],
    related_name: &str,
) -> Result<std::collections::HashMap<i64, Vec<R>>, OrmError>
where
    T: Model,
    R: Model + FromRow + Clone,
    E: djangors_db::DbExecutor,
{
    let parent_meta = T::meta();
    let child_meta = R::meta();
    let relation = child_meta
        .relations
        .iter()
        .find(|relation| {
            relation.related_name == Some(related_name)
                && (relation.target)().struct_name == parent_meta.struct_name
        })
        .ok_or_else(|| OrmError::FieldNotFound {
            field: format!("reverse relation '{}'", related_name),
            model: child_meta.struct_name,
        })?;
    let pk_field = parent_meta
        .fields
        .iter()
        .find(|field| field.primary_key)
        .ok_or_else(|| OrmError::FieldNotFound {
            field: "primary_key".to_string(),
            model: parent_meta.struct_name,
        })?;
    let parent_ids: Vec<i64> = parents
        .iter()
        .filter_map(|parent| {
            parent
                .field_values()
                .into_iter()
                .find(|(name, _)| *name == pk_field.name)
                .and_then(|(_, value)| match value {
                    Value::I64(id) => Some(id),
                    _ => None,
                })
        })
        .collect();

    let sql = format!(
        "SELECT * FROM \"{}\" WHERE \"{}\" = ANY($1)",
        child_meta.table_name, relation.field_name
    );
    let query = sqlx::query(sqlx::AssertSqlSafe(sql)).bind(parent_ids);
    db.record_query();
    let rows = db.conn().fetch_all(query).await?;
    let mut grouped = std::collections::HashMap::new();
    for row in rows {
        let child = R::from_row(&row)?;
        let parent_id = child
            .field_values()
            .into_iter()
            .find(|(name, _)| *name == relation.field_name)
            .and_then(|(_, value)| match value {
                Value::I64(id) => Some(id),
                _ => None,
            })
            .ok_or_else(|| OrmError::FieldNotFound {
                field: relation.field_name.to_string(),
                model: child_meta.struct_name,
            })?;
        grouped
            .entry(parent_id)
            .or_insert_with(Vec::new)
            .push(child);
    }
    Ok(grouped)
}

fn split_field_lookup(s: &'static str) -> (&'static str, &'static str) {
    if let Some(idx) = s.rfind("__") {
        let field = &s[..idx];
        let suffix = &s[idx + 2..];
        match suffix {
            "eq" | "lt" | "lte" | "gt" | "gte" | "contains" | "icontains" | "startswith"
            | "endswith" | "ne" | "iexact" | "in" | "isnull" | "regex" | "iregex" => {
                (field, suffix)
            }
            _ => (s, "eq"),
        }
    } else {
        (s, "eq")
    }
}

/// One row of a grouped aggregate query produced by
/// [`QuerySet::annotate`].
#[derive(Debug, Clone, PartialEq)]
pub struct GroupRow {
    /// The group-by field names paired with this group's values, in the order
    /// they were requested.
    pub keys: Vec<(&'static str, Value)>,
    /// The aggregate aliases paired with their results, in the order they were
    /// requested.
    pub aggregates: Vec<(String, crate::aggregate::AggResult)>,
}

impl GroupRow {
    /// Looks up a group-key value by field name.
    pub fn key(&self, name: &str) -> Option<&Value> {
        self.keys.iter().find(|(k, _)| *k == name).map(|(_, v)| v)
    }

    /// Looks up an aggregate result by alias.
    pub fn get(&self, alias: &str) -> Option<crate::aggregate::AggResult> {
        self.aggregates
            .iter()
            .find(|(k, _)| k == alias)
            .map(|(_, v)| *v)
    }
}

/// The field an aggregate targets (`"*"` for `COUNT(*)`).
fn agg_field(agg: &crate::aggregate::AggExpr) -> &'static str {
    match agg {
        crate::aggregate::AggExpr::Count { field }
        | crate::aggregate::AggExpr::Sum { field }
        | crate::aggregate::AggExpr::Avg { field }
        | crate::aggregate::AggExpr::Min { field }
        | crate::aggregate::AggExpr::Max { field } => field,
    }
}

/// Renders an aggregate as SQL. Non-count aggregates are cast to `float8` for
/// the same reason as in [`QuerySet::aggregate`]: Postgres's native result type
/// varies by both function and column type, and casting avoids having to decode
/// every combination client-side.
fn agg_sql(agg: &crate::aggregate::AggExpr, field_to_col: &dyn Fn(&str) -> String) -> String {
    match agg {
        crate::aggregate::AggExpr::Count { field } => {
            if *field == "*" {
                "COUNT(*)".to_string()
            } else {
                format!("COUNT({})", field_to_col(field))
            }
        }
        crate::aggregate::AggExpr::Sum { field } => {
            format!("SUM({})::float8", field_to_col(field))
        }
        crate::aggregate::AggExpr::Avg { field } => {
            format!("AVG({})::float8", field_to_col(field))
        }
        crate::aggregate::AggExpr::Min { field } => {
            format!("MIN({})::float8", field_to_col(field))
        }
        crate::aggregate::AggExpr::Max { field } => {
            format!("MAX({})::float8", field_to_col(field))
        }
    }
}

/// The declared [`FieldKind`] for `name`, or `None` when `name` is a relation
/// (which is always stored as a bigint id).
fn field_kind_of(name: &str, meta: &'static ModelMeta) -> Option<FieldKind> {
    meta.fields.iter().find(|f| f.name == name).map(|f| f.kind)
}

/// Decodes column `idx` of `row` into a [`Value`], guided by the model's
/// declared field kind. A `None` kind means a relation column, which is always
/// a bigint id. Anything that fails to decode becomes [`Value::Null`] rather
/// than an error, matching how the rest of the row mapper treats absent data.
fn decode_value(row: &sqlx::postgres::PgRow, idx: usize, kind: Option<FieldKind>) -> Value {
    use sqlx::Row;

    match kind {
        Some(FieldKind::Char)
        | Some(FieldKind::Text)
        | Some(FieldKind::Email)
        | Some(FieldKind::Url)
        | Some(FieldKind::Slug)
        | Some(FieldKind::Ip)
        | Some(FieldKind::FileField) => row
            .try_get::<Option<String>, _>(idx)
            .ok()
            .flatten()
            .map(Value::Text)
            .unwrap_or(Value::Null),
        Some(FieldKind::Float) => row
            .try_get::<Option<f64>, _>(idx)
            .ok()
            .flatten()
            .map(Value::F64)
            .unwrap_or(Value::Null),
        Some(FieldKind::Boolean) => row
            .try_get::<Option<bool>, _>(idx)
            .ok()
            .flatten()
            .map(Value::Bool)
            .unwrap_or(Value::Null),
        Some(FieldKind::DateTime) => row
            .try_get::<Option<chrono::DateTime<chrono::Utc>>, _>(idx)
            .ok()
            .flatten()
            .map(Value::DateTime)
            .unwrap_or(Value::Null),
        // Integer, BigInt, relations, and the kinds the derive macro already
        // rejects for save/update all decode as a bigint.
        _ => row
            .try_get::<Option<i64>, _>(idx)
            .ok()
            .flatten()
            .map(Value::I64)
            .unwrap_or(Value::Null),
    }
}

/// Binds one [`Value`] onto a query. Mirrors the inline bind matches used by
/// the row-returning paths, for the two call sites that have no per-field
/// `NullBindKind` context.
fn bind_value<'q>(
    query: sqlx::query::Query<'q, sqlx::Postgres, sqlx::postgres::PgArguments>,
    val: &'q Value,
) -> sqlx::query::Query<'q, sqlx::Postgres, sqlx::postgres::PgArguments> {
    match val {
        Value::I64(v) => query.bind(*v),
        Value::F64(v) => query.bind(*v),
        Value::Text(v) => query.bind(v.clone()),
        Value::Bool(v) => query.bind(*v),
        Value::DateTime(v) => query.bind(*v),
        Value::Null => query.bind(None::<i64>),
        Value::List(_) => query.bind(None::<i64>),
    }
}

fn suffix_to_op(suffix: &str) -> CompareOp {
    match suffix {
        "eq" => CompareOp::Eq,
        "lt" => CompareOp::Lt,
        "lte" => CompareOp::Lte,
        "gt" => CompareOp::Gt,
        "gte" => CompareOp::Gte,
        "contains" => CompareOp::Contains,
        "icontains" => CompareOp::IContains,
        "startswith" => CompareOp::StartsWith,
        "endswith" => CompareOp::EndsWith,
        "ne" => CompareOp::Ne,
        "iexact" => CompareOp::IExact,
        "in" => CompareOp::In,
        "isnull" => CompareOp::IsNull,
        "regex" => CompareOp::Regex,
        "iregex" => CompareOp::IRegex,
        _ => CompareOp::Eq,
    }
}

fn compile_expr_sql(
    expr: &Expr,
    field_to_col: &dyn Fn(&str) -> String,
    params: &mut Vec<Value>,
    param_idx: &mut usize,
) -> String {
    match expr {
        Expr::Compare { field, op, value } => {
            let col = field_to_col(field);

            // `IN` and `IS NULL` bind a variable number of parameters (N and
            // zero respectively), so they cannot go through the single-binding
            // operator table below.
            match op {
                CompareOp::In => {
                    let items: Vec<Value> = match value {
                        Value::List(items) => items.clone(),
                        // A bare scalar for `__in` is treated as a one-element
                        // list rather than an error, so `q!(id__in = 5)` works.
                        other => vec![other.clone()],
                    };
                    if items.is_empty() {
                        // `IN ()` is a syntax error; Django resolves an empty
                        // `__in` to a contradiction instead.
                        return "FALSE".to_string();
                    }
                    let mut placeholders = Vec::with_capacity(items.len());
                    for item in items {
                        params.push(item);
                        placeholders.push(format!("${}", param_idx));
                        *param_idx += 1;
                    }
                    return format!("{} IN ({})", col, placeholders.join(", "));
                }
                CompareOp::IsNull => {
                    // `isnull = false` inverts the test, as in Django.
                    let want_null = !matches!(value, Value::Bool(false));
                    return if want_null {
                        format!("{} IS NULL", col)
                    } else {
                        format!("{} IS NOT NULL", col)
                    };
                }
                _ => {}
            }

            let (op_sql, bind_val) = match op {
                CompareOp::In | CompareOp::IsNull => unreachable!("handled above"),
                CompareOp::Ne => ("<>", value.clone()),
                CompareOp::Regex => ("~", value.clone()),
                CompareOp::IRegex => ("~*", value.clone()),
                CompareOp::IExact => ("ILIKE", value.clone()),
                CompareOp::Eq => ("=", value.clone()),
                CompareOp::Lt => ("<", value.clone()),
                CompareOp::Lte => ("<=", value.clone()),
                CompareOp::Gt => (">", value.clone()),
                CompareOp::Gte => (">=", value.clone()),
                CompareOp::Contains => {
                    let s = match value {
                        Value::Text(t) => format!("%{}%", t),
                        other => format!("%{}%", other),
                    };
                    ("LIKE", Value::Text(s))
                }
                CompareOp::IContains => {
                    let s = match value {
                        Value::Text(t) => format!("%{}%", t),
                        other => format!("%{}%", other),
                    };
                    ("ILIKE", Value::Text(s))
                }
                CompareOp::StartsWith => {
                    let s = match value {
                        Value::Text(t) => format!("{}%", t),
                        other => format!("{}%", other),
                    };
                    ("LIKE", Value::Text(s))
                }
                CompareOp::EndsWith => {
                    let s = match value {
                        Value::Text(t) => format!("%{}", t),
                        other => format!("%{}", other),
                    };
                    ("LIKE", Value::Text(s))
                }
            };
            params.push(bind_val);
            let placeholder = format!("${}", param_idx);
            *param_idx += 1;
            format!("{} {} {}", col, op_sql, placeholder)
        }
        Expr::And(exprs) => {
            if exprs.is_empty() {
                "TRUE".to_string()
            } else {
                let parts: Vec<String> = exprs
                    .iter()
                    .map(|e| format!("({})", compile_expr_sql(e, field_to_col, params, param_idx)))
                    .collect();
                parts.join(" AND ")
            }
        }
        Expr::Or(exprs) => {
            if exprs.is_empty() {
                "FALSE".to_string()
            } else {
                let parts: Vec<String> = exprs
                    .iter()
                    .map(|e| format!("({})", compile_expr_sql(e, field_to_col, params, param_idx)))
                    .collect();
                parts.join(" OR ")
            }
        }
        Expr::Not(inner) => {
            format!(
                "NOT ({})",
                compile_expr_sql(inner, field_to_col, params, param_idx)
            )
        }
        Expr::CompareField { left, op, right } => {
            let lhs = field_to_col(left);
            let rhs = field_to_col(right);
            // Both sides are columns, so nothing is bound and the pattern-based
            // operators (LIKE/ILIKE) build their wildcards in SQL instead of in
            // a bind parameter.
            let sql = match op {
                CompareOp::Eq => format!("{} = {}", lhs, rhs),
                CompareOp::Ne => format!("{} <> {}", lhs, rhs),
                CompareOp::Lt => format!("{} < {}", lhs, rhs),
                CompareOp::Lte => format!("{} <= {}", lhs, rhs),
                CompareOp::Gt => format!("{} > {}", lhs, rhs),
                CompareOp::Gte => format!("{} >= {}", lhs, rhs),
                CompareOp::Contains => format!("{} LIKE '%' || {} || '%'", lhs, rhs),
                CompareOp::IContains => format!("{} ILIKE '%' || {} || '%'", lhs, rhs),
                CompareOp::StartsWith => format!("{} LIKE {} || '%'", lhs, rhs),
                CompareOp::EndsWith => format!("{} LIKE '%' || {}", lhs, rhs),
                CompareOp::IExact => format!("{} ILIKE {}", lhs, rhs),
                CompareOp::Regex => format!("{} ~ {}", lhs, rhs),
                CompareOp::IRegex => format!("{} ~* {}", lhs, rhs),
                // Neither makes sense against another column: `IN` needs a list
                // and `IS NULL` needs no right-hand side at all. Degrade to the
                // plain equality the user most likely meant.
                CompareOp::In | CompareOp::IsNull => format!("{} = {}", lhs, rhs),
            };
            sql
        }
    }
}
