use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let workspace_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("Failed to find workspace root");
    let docs_src = workspace_root.join("docs").join("src");

    println!("cargo:rerun-if-changed={}", docs_src.display());

    assert!(
        docs_src.exists(),
        "docs/src directory does not exist at {:?}",
        docs_src
    );

    let mut md_files = Vec::new();
    collect_md_files(&docs_src, &mut md_files);
    md_files.sort();

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let generated_path = out_dir.join("generated_snippets.rs");

    let mut generated_code = String::new();
    generated_code.push_str("// Generated by tools/doc-code-check/build.rs\n\n");

    let mut total_files = 0;
    let mut total_compile_blocks = 0;
    let mut total_illustrative_blocks = 0;
    let mut errors = Vec::new();

    for md_file in &md_files {
        total_files += 1;
        let content = fs::read_to_string(md_file).expect("Failed to read md file");
        let lines: Vec<&str> = content.lines().collect();

        let rel_path = md_file
            .strip_prefix(workspace_root)
            .unwrap_or(md_file)
            .display()
            .to_string();

        let mod_base = rel_path.replace(['/', '\\', '.', '-'], "_");

        let mut in_code_block = false;
        let mut block_start_line = 0;
        let mut block_tag = String::new();
        let mut block_lines: Vec<&str> = Vec::new();

        for (idx, line) in lines.iter().enumerate() {
            let line_num = idx + 1;
            let trimmed = line.trim();

            if !in_code_block {
                if trimmed.starts_with("```") {
                    let tag = trimmed.trim_start_matches('`').trim();
                    if tag == "rust" || tag.starts_with("rust,") || tag.starts_with("rust ") {
                        in_code_block = true;
                        block_start_line = line_num;
                        block_tag = tag.to_string();
                        block_lines.clear();
                    }
                }
            } else if trimmed == "```" {
                in_code_block = false;

                if block_tag == "rust" {
                    errors.push(format!(
                        "UNTAGGED CODE BLOCK in {}:{}: Bare ```rust block found. Must be tagged ```rust,compile or ```rust,illustrative.",
                        rel_path, block_start_line
                    ));
                } else if block_tag == "rust,illustrative" {
                    total_illustrative_blocks += 1;
                } else if block_tag == "rust,compile" {
                    total_compile_blocks += 1;

                    let mut processed_lines = Vec::new();
                    for bl in &block_lines {
                        if let Some(stripped) = bl.strip_prefix("# ") {
                            processed_lines.push(stripped.to_string());
                        } else if *bl == "#" {
                            processed_lines.push(String::new());
                        } else {
                            processed_lines.push(bl.to_string());
                        }
                    }

                    let mod_name = format!("snippet_{}_{}", mod_base, block_start_line);
                    generated_code.push_str(&format!(
                        "#[allow(clippy::all, unused_imports, unused_variables, dead_code, unused_mut, async_fn_in_trait, unreachable_code)]\npub mod {} {{\n",
                        mod_name
                    ));
                    for pl in processed_lines {
                        generated_code.push_str("    ");
                        generated_code.push_str(&pl);
                        generated_code.push('\n');
                    }
                    generated_code.push_str("}\n\n");
                } else {
                    errors.push(format!(
                        "INVALID CODE BLOCK TAG in {}:{}: Tag '{}' is not recognized. Must be ```rust,compile or ```rust,illustrative.",
                        rel_path, block_start_line, block_tag
                    ));
                }
            } else {
                block_lines.push(*line);
            }
        }

        if in_code_block {
            errors.push(format!(
                "UNCLOSED CODE BLOCK in {}:{} starting at line {}",
                rel_path, block_start_line, block_start_line
            ));
        }
    }

    if !errors.is_empty() {
        panic!(
            "\nDoc code block verification failed during build with {} error(s):\n\n{}\n",
            errors.len(),
            errors.join("\n----------------------------------------\n")
        );
    }

    generated_code.push_str(&format!(
        "pub const TOTAL_FILES: usize = {};\n",
        total_files
    ));
    generated_code.push_str(&format!(
        "pub const TOTAL_COMPILE_BLOCKS: usize = {};\n",
        total_compile_blocks
    ));
    generated_code.push_str(&format!(
        "pub const TOTAL_ILLUSTRATIVE_BLOCKS: usize = {};\n",
        total_illustrative_blocks
    ));

    fs::write(&generated_path, generated_code).expect("Failed to write generated_snippets.rs");
}

fn collect_md_files(dir: &Path, files: &mut Vec<PathBuf>) {
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                collect_md_files(&path, files);
            } else if path.extension().is_some_and(|ext| ext == "md") {
                files.push(path);
            }
        }
    }
}
