[package]
name = "djangors-staticfiles"
description = "Static files support for Djangors"
repository = "https://github.com/Chidi09/djangors"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = []
clamav = ["tokio/net", "tokio/io-util"]

[dependencies]
thiserror = "2.0.18"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
djangors-core = { path = "../djangors-core", version = "0.6.0" }
sha2 = "0.10.9"
hyper = "1.10"
async-trait = "0.1.86"
tokio = { version = "1.53.0", features = ["rt"] }
s3 = "0.1.36"

[dev-dependencies]
tempfile = "3.27.0"
tokio = { version = "1.53.0", features = ["full"] }
bytes = "1.12"
