[package]
name = "djangors-migrations"
description = "Migration engine with autodetection for Djangors"
repository.workspace = true
homepage.workspace = true
readme = "README.md"
keywords = ["django", "web-framework", "migrations", "schema", "ddl"]
categories = ["database"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
djangors-orm = { path = "../djangors-orm", version = "0.6.0" }
djangors-db = { path = "../djangors-db", version = "0.6.0" }
thiserror = "2.0.18"
sqlx = { version = "0.9.0", features = ["runtime-tokio", "postgres", "sqlite", "chrono"] }
serde_json = "1.0.150"
tokio = { version = "1.53.0", features = ["rt", "macros"] }

[dev-dependencies]
djangors-macros = { path = "../djangors-macros" }
djangors-test = { path = "../djangors-test" }
