[package]
name = "djangors-forms"
description = "Forms and validation for the Djangors web framework"
repository.workspace = true
homepage.workspace = true
readme = "README.md"
keywords = ["django", "web-framework", "forms", "validation", "html-forms"]
categories = ["web-programming"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
djangors-macros = { path = "../djangors-macros", version = "0.6.0" }

