[package]
name = "djangors-forms"
description = "Forms and validation for the Djangors web framework"
repository = "https://github.com/Chidi09/djangors"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
djangors-macros = { path = "../djangors-macros", version = "0.2.0" }

