[package]
name = "djangors-macros"
description = "Proc macros for the Djangors web framework"
repository.workspace = true
homepage.workspace = true
readme = "README.md"
keywords = ["django", "web-framework", "proc-macro", "derive", "macros"]
categories = ["development-tools::procedural-macro-helpers"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"

[dev-dependencies]
trybuild = "1.0"
djangors-orm = { path = "../djangors-orm" }
djangors-forms = { path = "../djangors-forms" }
djangors-core = { path = "../djangors-core" }

