[package]
name = "djangors-core"
description = "HTTP kernel for the Djangors web framework"
repository = "https://github.com/Chidi09/djangors"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = []
sentry = ["dep:sentry", "dep:sentry-tracing"]

[dependencies]
sentry = { version = "0.34", optional = true, default-features = false, features = ["backtrace", "contexts", "panic", "reqwest", "rustls"] }
sentry-tracing = { version = "0.34", optional = true }
hyper = { version = "1.10.1", features = ["http1", "server"] }
hyper-util = { version = "0.1.20", features = ["server-auto", "tokio", "service"] }
http-body-util = "0.1.4"
bytes = "1.12.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
thiserror = "2.0.18"
percent-encoding = "2.3.2"
tokio = { version = "1.53.0", features = [
    "net",
    "rt-multi-thread",
    "macros",
    "io-util",
    "signal",
    "time",
    "sync",
] }
tokio-stream = { version = "0.1.17", features = ["sync"] }
futures-util = "0.3.31"
tower = { version = "0.5.3", features = ["util"] }
tower-http = { version = "0.7.0", features = [
    "trace",
    "compression-gzip",
    "compression-br",
    "set-header",
    "normalize-path",
    "request-id",
    "util",
] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["fmt", "env-filter", "json"] }
toml = "0.8.20"
async-trait = "0.1.86"
serde_urlencoded = "0.7.1"
multer = "3.1.0"
rand = "0.8.7"
base64 = "0.22.1"
djangors-orm = { path = "../djangors-orm", version = "0.2.1" }
djangors-cache = { path = "../djangors-cache", version = "0.2.1" }
inventory = "0.3.24"

[dev-dependencies]
djangors-db = { path = "../djangors-db" }
djangors-orm = { path = "../djangors-orm" }
djangors-macros = { path = "../djangors-macros" }
sqlx = { version = "0.9.0", features = ["runtime-tokio", "postgres"] }
